<?php
/**
 * 志愿服务报名列表 模型
 */
namespace Admin\Model;
use Think\Model\RelationModel;

class VolunteerServicePartnerModel extends RelationModel {
    protected $tableName="volunteer_service_partner";
    protected $_validate = array(
        array('volunteer_id','require','记录不合法',1),
    );
    // 自动完成
    protected $_auto = array (
        array('uid', 'uid', 1, 'function'),
        array('create_at', 'time', 1, 'function'),
    );

    protected $uid;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->uid = intval(uid());
    }

    /**
     * 报名
     */
    public function signUp($volunteerId)
    {
      try {
        $this->startTrans();
        if($this->checkSignUp($volunteerId)) throw new \Exception('不能重复报名哦!');
        $post = array('volunteer_id' => $volunteerId);
        if (!$this->create($post)) throw new \Exception($this->getError());
        $id = $this->add();
        if (!$id) throw new \Exception('报名发生错误！请稍后重试..');
        $bool = M('VolunteerService')->where(array('id' => $volunteerId))->setInc('total');
        if(!$bool) throw new \Exception('更新数据发生异常！请稍后重试..');
        $this->sendWechatMessage($volunteerId);// 推送微信消息
        $this->commit();
        return true;
      } catch (\Exception $e) {
        $this->rollback();
        return $e->getMessage();
      }

    }

    /**
     * 检查是否报名
     * @return bool 已报名返回 true 否则返回 false
     */
    public function checkSignUp($volunteerId) {
      $uid = $this->uid;
      $id=$this->where(array('volunteer_id' => $volunteerId,'uid' => $uid))->getField('id');
      if ($id) return true;
      return false;
    }

    protected function sendWechatMessage($volunteerId)
    {
        $info = M('VolunteerService')->field('theme,address,start_date')->find($volunteerId);
        $title = $info['theme'].'活动报名成功';
        $description = '开始日期:'.$info['start_date'].'<br/>服务地点:'.$info['address'];
        $url = C('DOMAIN').'/vue-project/pages/VolunteerDetail/index.html?id='.$volunteerId;
        $user = user();
        pushQyWechatMessage($user['qyuserid'], $title, $description, $url);
    }
}
