<?php
namespace Admin\Controller;

use Common\Controller\BaseController;
use Common\Util\ImageUploadUtil;
use Think\Controller;
use Weixin\Util\QYConfig;
use Admin\Util\AdminUtil;

/**
 *
 */
class AutoMatchController extends BaseAdminController
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->set_sidebar_module('PartyWorking');

    }
    function auto($type,$value){//$type 类型(判断传进来的是哪个层级的id)  $value  id值
        if($type == "group_id"){
            $upid =  D("PartyGroup")->where("id=$value")->field('branch_id,branch_hq_id,work_id,working_id')->find();
        } elseif($type == "branch_id"){
            $upid =  D("PartyBranch")->where("id=$value")->field('branch_hq_id,work_id,working_id')->find();
        } elseif($type == "branch_hq_id"){
             $upid =  D("PartyBranchHq")->where("id=$value")->field('work_id,working_id')->find();
        }elseif($type == "work_id"){
            $upid =  D("PartyOrganization")->where("id=$value")->field('working_id')->find();
        }else{

        }
        ajaxMsg(0, '查询成功',$upid);
    }
}