<?php
namespace Admin\Controller;

use Admin\Model\AdminAuthRuleViewModel;
use Common\Controller\BaseController;
use Think\Controller;
use Admin\Util\AdminUtil;

/**
 * 文章管理
 * Class ContentController
 * @package Home\Controller
 */
class ContentController extends BaseAdminController
{

	function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->set_sidebar_module('Content');
		$this->set_sidebar_sub('index');
	}

    public function index()
    {
        // admin()获取登陆的管理员信息
		// $admin = admin();
        // 获取是哪个权限
		$auth = AdminUtil::auth();
		$map = array();
		// if($auth == 2){//总支
		// 	$map['Articles.branch_hq_id'] = $admin['admin_branch_hq_id'];
		// }session_auth
        // 等于3为支部权限，$admin['admin_branch_id'] 是支部id
		if($auth == 3){//支部
            $branch = AdminUtil::auth_branch();
			$map['branch_id'] = $branch['id'];
		}

		$map['status']=array('gt',0);
        $keyword = I('keyword');
        if ($keyword) {
            $map['title'] = array('like', '%' . $keyword . '%');
            $this->assign('keyword',$keyword);
        }


    	// $this->assign('articles',D('ArticlesView')->findPage($map,15,'id desc'));
        $this->assign('articles',D('Articles')->findPage($map,15,'id desc'));
    	// $this->assign('branchs',D('PartyBranch')->select());
    	$this->assign('tags',M('tags')->where("type_name='article'")->select());
   	    // echo to_json_string(D('Articles')->findPage($map,15,'id desc'));

        $this->display();
    }

    public function add($id=0)
    {
    	if ($id > 0) {
    		$condition['id'] = $id;
    		$article=D('Articles')->where($condition)->relation(true)->find();
    		$this->assign('article_tags',D('ArticlesTagsView')->where(array('article_id'=>$article['id']))->select());
    		$this->assign('article',$article);
    		// echo to_json_string($article_tags);
    	}
    	$this->assign('p', I('get.p',1));
    	$this->assign('tags',M('tags')->where("type_name='article'")->select());
        $this->display();
    }

    #新增文章 ajax提交
    public function ajaxAdd($id = 0)
    {
        $auth = AdminUtil::auth();
        if ($auth != 3) {
            $auth =1;
        }
    	if ($auth > 0 && $auth < 4){
    		$data['title'] = I('post.title');
    		// $data['is_index'] = I('post.is_index');
    		$data['hidden'] = I('post.hidden');
    		$data['content'] = $_POST['content'];
    		$data['create_at'] = time();
    		$data['cover_path'] = I('post.img_url');
            $data['spider_url'] = I('post.spider_url');
            $data['is_url'] = I('post.is_url');
            // $data['meeting_at'] = strtotime(I('post.meeting_at'));
    		$tags = I('post.tags');
    		// $tags = array(1, 2);
    		$article_tag = I('post.article_tag');
    		if ($data['hidden'] == 1) {
    			$data['published_at'] = time();
    		}
    		$id = I('post.id');
    		$articleModal = D('Articles');
    		if ($id > 0 && !empty($id)) {
    			$old_article = $articleModal -> where(array('id'=>$id)) -> find();
    			if ($old_article) {
  					$data["id"] = $old_article["id"];
    			}else{
   					ajaxMsg(1, $articleModal->getError());
   				}	
    		}
            if ($auth == 3) {
                    $branch = AdminUtil::auth_branch();
                    $data['branch_id'] = $branch['id'];
                }
    		$article = $articleModal -> create($data);
    		$articles_tags = D('ArticlesTags');
    		if ($old_article) {
				if($auth > 0) {
					$articleModal->save($article);
					$articles_tags->where(array('article_id' => $article["id"]))->delete();
					$tag_data['article_id'] = $article["id"];
				}
                // $old_article_tags = $articles_tags->where(array('article_id'=>$article['id']));
                // $diff_tags = array_intersect($old_article_tags,$tags);
            } else {
                    $add_user=AdminUtil::admin();
					$article['uid'] = $add_user['uid'];
					// $article = set_save_auth($article);

					$article_id = $articleModal->add($article);
					$tag_data['article_id'] = $article_id;

            }
			foreach ($tags as $id) {
                // if ($id == 4) {
                //     $tag_data['second_tag_id'] = I('post.qt_tag');
                // }elseif ($id == 15) {
                //     $tag_data['second_tag_id'] = I('post.shyk_tag');
                // }elseif ($id == 17) {
                //     $tag_data['second_tag_id'] = I('post.mzshh_tag');
                // }
				$tag_data['tag_id'] = $id;
				$articles_tags->add($tag_data);
			};
            ajaxMsg(0, '保存成功');
    	}else{

    	}

    }

     //删除文章
    public function ajaxDecContent(){
        $id = I('post.id');
        $article = D('Articles')->find($id);
        if($article){
            $article["status"]=0;
            D('Articles')->save($article);
            ajaxMsg(0, "已删除");
        }else{
            ajaxMsg(1,'文章不存在');
        }
    }
     //启动禁止文章
    public function ajaxHiddenContent(){
        $id = I('post.id');
        $article = D('Articles')->find($id);
        if($article){
            if ($article["hidden"]==0) {
                $article["hidden"]=1;
                D('Articles')->save($article);
                ajaxMsg(0, "已启动");
            }elseif ($article["hidden"]==1) {
                $article["hidden"]=0;
                D('Articles')->save($article);
                ajaxMsg(0, "已禁止");
            }
            
            
        }else{
            ajaxMsg(1,'文章不存在');
        }
    }

}