<?php
namespace Admin\Controller;

use Admin\Model\AdminAuthRuleViewModel;
use Common\Controller\BaseController;
use Think\Controller;
use Admin\Util\AdminUtil;

/**
 * 文章管理
 * Class ContentController
 * @package Home\Controller
 */
class NormController extends BaseAdminController
{

	function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->set_sidebar_module('Norm');
		$this->set_sidebar_sub('index');
	}

    public function index()
    {
        $map = array();
        $keyword = I('keyword','');
        $map['status']=array('gt',0);
        if ($keyword) {
            $map['title'] = array('like', '%' . $keyword . '%');
            $this->assign('keyword',$keyword);
        }
        $this->assign('articles',D('NormView')->findPage($map,15,'order_id'));

        $this->display();
    }

    public function add($id=0)
    {
    	if ($id > 0) {
    		$condition['id'] = $id;
    		$article=D('Norm')->where($condition)->find();
    	
    		$this->assign('article',$article);
    		// echo to_json_string($article_tags);
    	}
    	$this->assign('p', I('get.p',1));
    
        $this->display();
    }

    #新增文章 ajax提交
    public function ajaxAdd($id = 0)
    {
        $id = I('id');
        $content = I('content');
        $title = I('title');
        $order_id = I('order_id');
        $chapter = I('chapter');
        $data['content'] =htmlspecialchars_decode($content);
        $data['title'] = $title;
        $data['chapter'] = $chapter;
        $data['order_id'] = $order_id;
       
        if($id){
            $data['update_time'] = time();
            //更新
            $check = D('Norm')->where(array('id'=>$id))->find();
            if(!$check){
                ajaxMsg(1, "id不存在");
            }
         
            $result = D('Norm')->where(array('id'=>$id))->save($data);
        }else{
            //新增
            $data['create_time'] = time();
            $data['update_time'] = time();
            $result = D('Norm')->add($data);
        }
        ajaxMsg(0, "保存成功");

    }

     //删除文章
    public function ajaxDecContent(){
        $id = I('post.id');
        $article = D('Norm')->find($id);
        if($article){
            $article["status"]=0;
            D('Norm')->save($article);
            ajaxMsg(0, "已删除");
        }else{
            ajaxMsg(1,'文章不存在');
        }
    }
  

}