<?php
namespace Admin\Controller;

use Common\Controller\BaseController;
use Think\Controller;

/**
 * 支部管理
 * Class SystemController
 * @package Admin\Controller
 */
class NoticeController extends BaseAdminController
{

    function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->set_sidebar_module('Notice');
		$this->set_sidebar_sub('index');
	}

    public function index(){
    	$map['status']=1;
    	$notices=D('NoticeView')->findPage($map,15,'id desc');
        $this->assign("notices",$notices);
    	$this->display();
    }

    public function add(){
    	$notice_types=D('NoticeType')->select();
        $this->assign("notice_types",$notice_types);
        $this->assign('p', I('get.p',1));
    	$this->display();
    }

    public function ajaxDec(){
        $id = I('post.id');
        $notice = D('Notice')->find($id);
        if($notice){
            $notice["status"]=-1;
            D('Notice')->save($notice);
            D('NoticeUserStatus')->where(array('notice_id'=>$notice['id'],'status'=>1))->save(array('status'=>-1));
            ajaxMsg(0, "已删除");
        }else{
            ajaxMsg(1,'待办事项不存在');
        }
    }

    public function ajaxAdd(){
    	$data['content']=I('post.content');
    	$data['publish_time']=I('post.publish_time');
    	$data['finish_time']=I('post.finish_time');
    	$data['type_id']=I('post.type_id');
        $data['create_time']=time();
    	if (!$data['type_id']) {
    		ajaxMsg(1, '请选择代办类型');
    	}
    	if (!$data['publish_time']) {
    		ajaxMsg(1, '请填写代办事项的开始时间');
    	}
    	if (!$data['finish_time']) {
    		ajaxMsg(1, '请填写代办事项的结束时间');
    	}
    	if (!$data['content']) {
    		ajaxMsg(1, '请填写代办事项的内容');
    	}
    	$data['publish_time']=strtotime($data['publish_time']);
    	$data['finish_time']=strtotime($data['finish_time'])+86399;
        if($data['type_id'] == 1 || $data['type_id'] == 2 || $data['type_id'] == 3){
            $data['taizhang_type']=2;
        }elseif($data['type_id'] == 7){
            $data['taizhang_type']=3;
        }else{
            $data['taizhang_type']=4;
        }
    	$notice_id=D('Notice')->add($data);
        $this->addUserNoticeStatus($notice_id,$data['type_id']);
    	ajaxMsg(0, '1');
    }

    public function user(){
    	$notice_id=I('get.id');
    	$map['notice_id']=$notice_id;
    	$map['status']=1;
    	$notice_user=D('NoticeUserStatusView')->findPage($map,15,'id desc');
        $this->assign("notice_user",$notice_user);
    	$this->display();
    }

    public function test(){
        // $user=D('PartyBranch')->relation(true)->select();
       $where='';
            $where['status']=1;
            $where['organization_id']=array(array('gt',0));
            // $where['sj_uid']=null;
            $dz_adm=D('UserOrganizationAdmView')->where($where)->select();
            $party=D('User')->where(array('post_id'=>1,'status'=>1,'branch_id'=>array('gt',0)))->select();
            // D('user')->where(array('organization_id'=>15))->save(array('organization_id'=>null));
        echo to_json_string($party); 
    }

    private function addUserNoticeStatus($notice_id,$type_id){
    	if ($type_id == 1) {
    		$dangzu=D('PartyOrganizationMsView')->select();
    		
    		foreach($dangzu as $vo){
                if ($vo['ms_uid']) {
                    D('NoticeUserStatus')->add(array("uid"=>$vo['ms_uid'],"notice_id"=>$notice_id,"add_taizhang_uid"=>$vo['ms_uid'],"create_time"=>time(),"organization_id"=>$vo['id']));
                }
    			$users=D('User')->where(array("organization_id"=>$vo['id'],"status"=>1))->select();
    			foreach($users as $user){
    				D('NoticeUserStatus')->add(array("uid"=>$user['uid'],"notice_id"=>$notice_id,"add_taizhang_uid"=>$vo['ms_uid'],"is_main"=>1,"create_time"=>time(),"organization_id"=>$vo['id']));
    			}
    		}
    	}elseif ($type_id == 2) {
            $dangzu=D('PartyOrganizationMsSjView')->select();
            
            foreach($dangzu as $vo){
                if ($vo['ms_uid']) {
                    D('NoticeUserStatus')->add(array("uid"=>$vo['ms_uid'],"notice_id"=>$notice_id,"add_taizhang_uid"=>$vo['ms_uid'],"create_time"=>time(),"organization_id"=>$vo['id']));
                }
                if ($vo['sj_uid']) {
                    D('NoticeUserStatus')->add(array("uid"=>$vo['sj_uid'],"notice_id"=>$notice_id,"add_taizhang_uid"=>$vo['ms_uid'],"is_main"=>1,"create_time"=>time(),"organization_id"=>$vo['id']));
                }
                
                
            }
        }elseif ($type_id == 3) {
            $where='';
            $where['status']=1;
            $where['organization_id']=array(array('gt',0));
            // $where['sj_uid']=null;
            $dz_adm=D('UserOrganizationAdmView')->where($where)->select();

            foreach($dz_adm as $vo){
                $add_taizhang_uid = $vo['uid'];
                if ($vo['sj_uid'] == null || $vo['sj_uid']=='') {
                    if ($vo['admin_uid']) {
                        $add_taizhang_uid = $add_taizhang_uid . ',' . $vo['admin_uid'];
                        D('NoticeUserStatus')->add(array("uid"=>$vo['admin_uid'],"notice_id"=>$notice_id,"add_taizhang_uid"=>$add_taizhang_uid,"create_time"=>time(),"organization_id"=>$vo['id']));
                    }
                    if ($vo['uid']) {
                        D('NoticeUserStatus')->add(array("uid"=>$vo['uid'],"notice_id"=>$notice_id,"add_taizhang_uid"=>$add_taizhang_uid,"is_main"=>1,"create_time"=>time(),"organization_id"=>$vo['id']));
                    }
                    
                }
                
                
                
                
            }
        }elseif ($type_id == 4) {
            $user=D('User')->where(array('branch_id'=>56,"status"=>1))->select();
            $adminUser=D('PartyBranchAdm')->where(array('branch_id'=>56))->select();
            $add_taizhang_uid = '';
            foreach($adminUser as $i=>$vo){
                if ($i == 0) {
                    $add_taizhang_uid=$vo['uid'];
                }else{
                    $add_taizhang_uid=$add_taizhang_uid . ',' . $vo['uid'];
                }
                  
            }
            foreach($user as $vo){
                    D('NoticeUserStatus')->add(array("uid"=>$vo['uid'],"notice_id"=>$notice_id,"add_taizhang_uid"=>$add_taizhang_uid,"is_main"=>1,"create_time"=>time(),'branch_id'=>56));
            }
        }elseif ($type_id == 5) {
            $user=D('User')->where(array('branch_id'=>51,"status"=>1))->select();
            $adminUser=D('PartyBranchAdm')->where(array('branch_id'=>51))->select();
            $add_taizhang_uid = '';
            foreach($adminUser as $i=>$vo){
                if ($i == 0) {
                    $add_taizhang_uid=$vo['uid'];
                }else{
                    $add_taizhang_uid=$add_taizhang_uid .','.$vo['uid'];
                }
                  
            }
            foreach($user as $vo){
                    D('NoticeUserStatus')->add(array("uid"=>$vo['uid'],"notice_id"=>$notice_id,"add_taizhang_uid"=>$add_taizhang_uid,"is_main"=>1,"create_time"=>time(),'branch_id'=>51));
            }
        }elseif ($type_id == 6) {
            $branchs=D('PartyBranch')->relation(true)->select();
            foreach ($branchs as $index => $vo) {
                $add_taizhang_uid='';
                foreach( $vo['admins'] as $i=>$admin){
                  if ($i == 0) {
                      $add_taizhang_uid=$admin['uid'];
                  }else{
                      $add_taizhang_uid=$add_taizhang_uid . ',' . $admin['uid'];
                  }
                }

                foreach( $vo['users'] as $i=>$user){
                   D('NoticeUserStatus')->add(array("uid"=>$user['uid'],"notice_id"=>$notice_id,"add_taizhang_uid"=>$add_taizhang_uid,"is_main"=>1,"create_time"=>time(),'branch_id'=>$vo['id']));
                }
            }
        }elseif ($type_id == 7) {
            $party_hq=D('PartyBranchHq')->select();
            foreach ($party_hq as $key => $vo) {
                if($vo['sj_uid']){
                    $add_taizhang_uid=$vo['sj_uid'];
                    if($vo['adm_uid']){
                        $add_taizhang_uid=$add_taizhang_uid.','.$vo['adm_uid'];
                        D('NoticeUserStatus')->add(array("uid"=>$vo['adm_uid'],"notice_id"=>$notice_id,"add_taizhang_uid"=>$add_taizhang_uid,"create_time"=>time(),'branch_hq_id'=>$vo['id']));
                    }
                    D('NoticeUserStatus')->add(array("uid"=>$vo['sj_uid'],"notice_id"=>$notice_id,"add_taizhang_uid"=>$add_taizhang_uid,"is_main"=>1,"create_time"=>time(),'branch_hq_id'=>$vo['id']));
                }
            }
            $party=D('User')->where(array('post_id'=>1,'status'=>1,'branch_id'=>array('gt',0)))->select();
            foreach ($party as $key => $vo) {
                $adm=D('PartyBranchAdm')->where(array('branch_id'=>$vo['branch_id']))->select();
                $add_taizhang_uid=$vo['uid'];
                foreach($adm as $i=>$admin){
                  // if ($i == 0) {
                  //     $add_taizhang_uid=$add_taizhang_uid.$admin['uid'];
                  // }else{
                      $add_taizhang_uid=$add_taizhang_uid . ',' . $admin['uid'];
                  // }
                }
                foreach($adm as $i=>$admin){
                    D('NoticeUserStatus')->add(array("uid"=>$admin['uid'],"notice_id"=>$notice_id,"add_taizhang_uid"=>$add_taizhang_uid,"create_time"=>time(),'branch_id'=>$vo['branch_id']));
                }
                D('NoticeUserStatus')->add(array("uid"=>$vo['uid'],"notice_id"=>$notice_id,"add_taizhang_uid"=>$add_taizhang_uid,"is_main"=>1,"create_time"=>time(),'branch_id'=>$vo['branch_id']));
            }

        }

    }




}