<?php
namespace Admin\Controller;

use Admin\Model\AdminAuthRuleViewModel;
use Common\Controller\BaseController;
use Common\Util\ImageUploadUtil;
use Think\Controller;

/**
 * 文章管理
 * Class ContentController
 * @package Home\Controller
 */
class PartyOrganizationController extends BaseAdminController
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->set_sidebar_module('PartyBranch');
        $this->set_sidebar_sub('partyOrganization');
    }
    function ajaxUploadCover(){

        ajaxMsg(0, "success", ImageUploadUtil::upload("organization/cover/",'file',array('width'=>200,'height'=>200),array('width'=>80,'height'=>80)));
    }

    public function index()
    {

        $map = array();

        $keyword = I('keyword');
        if ($keyword) {
            $map['PartyOrganization.name'] = array('like', '%' . $keyword . '%');
        }
        $this->assign('search',array('keyword'=>$keyword));

        $page =D('PartyOrganizationView')->find_page($map,'', 'PartyOrganization.id', 'PartyOrganization.sort desc');
        foreach($page['list'] as $index=>$item){
            $page['list'][$index]['intro'] = str_replace(array("\r\n", "\r", "\n"),"<br>", $item['intro']);//换行替换显示
            //获取对应上级组织
            $working_id = $item['working_id'];
            if($working_id){
                $page['list'][$index]['working_name'] = D('PartyWorking')->where("id=$working_id")->field('name')->find();
            }
        }
        $this->assign('page', $page);

        $this->display();
    }
    //党组成员
    public function member(){
        $organization_id = I('id');
        $Organization =D('PartyOrganizationMembers')->where("organization_id=$organization_id")->select();//取党工委成员列表
        $Organization = dutyorder($Organization);//按职务排序
        $Organizationname =D('PartyOrganization')->where("id=$organization_id")->field('name')->find();//取党工委名称
        $this->assign('organization_id', $organization_id);
        $this->assign('Organization', $Organization);
        $this->assign('Organizationname', $Organizationname);
        $this->display();
    }
    public function memberold(){
        $map = array();
        $id = I('id');

        $keyword = I('keyword');
        if ($keyword) {
            $map['User.realname'] = array('like', '%' . $keyword . '%');
        }
        $map['User.organization_id'] = $id;
        $this->assign('search',array('keyword'=>$keyword));

        $page =D('UserOrganizationView')->find_page($map,'', 'User.uid', 'PartyOrganizationSj.id desc');
        foreach($page['list'] as $index=>$item){
            $page['list'][$index]['intro'] = str_replace(array("\r\n", "\r", "\n"),"<br>", $item['intro']);//换行替换显示
        }
        $this->assign('page', $page);
        $this->assign('detail', D('PartyOrganization')->find($id));

        $this->display();
    }

    public function  ajaxGetUsers()
    {

//ajaxMsg(1,to_json_string($_POST));
        $id = I('id', 0);
        $keyword = I('keyword', '');
        $type = I('type','adm');
        $p_uid = I('uid');
        $list = D('UserOrganizationView')->where("User.status=1 and User.realname like '%$keyword%'")->group('User.uid')->order('User.realname asc')->limit(0, 20)->select();
        foreach ($list as $index => $item) {
            $uid = $item["uid"];
            $realname = $item['realname'];
            $branch_name = $item['branch_name'];
            if($branch_name){
                $name = $item['realname'] . "[$branch_name]".$item['mobile'];
            }else{
                $name = $item['realname'].$item['mobile'];
            }
            $item['html'] = "<a style='color: black;cursor: pointer;'><div class='item canselect' data-id='$uid' data-name='$realname'>$name</div></a>";
            if($type == 'adm'){
                if($item['adm_organization_uid']){
                    $show = true;
                    if($id){
                        if($p_uid){
                            if($item['adm_organization_uid'] == $p_uid){
                                $show = false;
                            }
                        }elseif($item['organization_id'] == $id){
                            $show = false;
                        }
                    }
                    if($show){
                        $item['html'] = "<div class='item un' data-id='$uid' >$name<div class='item-right'>[{$item['adm_organization_name']}-{$item['adm_organization_realname']}-管理员]</div></div>";
                    }
                }
            }elseif($type == 'ms'){
                if($item['ms_uid']){
                    $show = true;
                    if($id){
                        if($item['ms_organization_id'] == $id){
                            $show = false;
                        }
                    }
                    if($show){
                        $item['html'] = "<div class='item un' data-id='$uid' >$name<div class='item-right'>[{$item['ms_organization_name']}-秘书]</div></div>";
                    }
                }
            }else{
                if($item['organization_id']){
                    $show = true;
                    if($id){
                        if($item['organization_id'] == $id){
                            $show = false;
                        }
                    }
                    if($show){
                        $item['html'] = "<div class='item un' data-id='$uid' >$name<div class='item-right'>[{$item['organization_name']}-成员]</div></div>";
                    }
                }
            }

            $list[$index] = $item;
        }

        ajaxMsg(0, 'success', $list);

    }


    public function edit($id = 0)
    {
        if ($id > 0) {
            $condition['PartyOrganization.id'] = $id;
            $detail = D('PartyOrganizationView')->where($condition)->group('PartyOrganization.id')->find();
            $this->assign('detail', $detail);
//exit(to_json_string($detail));
        }
        $Working = D('PartyWorking')->select();
        $this->assign('Working', $Working);
        $this->assign('p', I('get.p', 1));
        $this->display();
    }
    public function edit_member()
    {
        $id = I('id');
        $organization_id=I('organization_id');
        if ($id > 0) {
            $condition['User.uid'] = $id;
            $detail = D('UserOrganizationView')->where($condition)->group('User.uid')->find();

            $this->assign('detail', $detail);
            $this->assign('organization_id', $detail['organization_id']);
        }elseif ($organization_id > 0){
            $this->assign('organization_id', $organization_id);
        }

        $this->assign('p', I('get.p', 1));
        $this->display();
    }


    public function ajaxDec($id = 0){
        $auth = session_auth();
        if($auth == 1){
            D('PartyOrganizationBranchs')->where(array('organization_id'=>$id))->delete();
            D('PartyOrganization')->where(array('id'=>$id))->delete();
        }
        ajaxMsg(0, '删除成功');
    }
//    public function ajaxDecMember($id = 0){
//    	$user = D('User')->find($id);
//    	 D('PartyOrganizationAdm')->where(array('organization_id'=>$user['organization_id'],'organization_uid'=>$id))->delete();
//            D('User')->where(array('uid'=>$id))->save(array('organization_id'=>null));
//        ajaxMsg(0, '删除成功');
//    }
    public function ajaxDecMember($id = 0){
        D('PartyOrganizationMembers')->where(array('id'=>$id))->delete();
        ajaxMsg(0, '删除成功');
    }

    public function ajaxSave()
    {

//        ajaxMsg(1,to_json_string($_POST));
        $id = I('id');
        $name = I('name');
        $ms_uid = I('ms_uid');
        $intro = $_POST['intro'];
        $sort = I('sort');

        $working_id = I('workingid');
        if(!$sort){
            $sort = 0;
        }
        if (!$name) {
            ajaxMsg(1, '请先填写党组名称');
        }
        $array = array(
            'sort'=>$sort,
            'name' => $name,
            'intro' => $intro,
            'cover'=>I('cover_path'),
            'working_id' =>$working_id,
        );


        if($ms_uid){
            $sj =  D('PartyOrganizationMs')->where(array('uid'=>$ms_uid))->find();
            if($sj && $sj['organization_id'] != $id){
                $dangzu = D('PartyOrganization')->find($sj['organization_id']);
                ajaxMsg(1,"该用户已担任{$dangzu['name']}的秘书");
            }
        }



        if ($id) {
            $detail = D('PartyOrganization')->find($id);
            if (!$detail) {
                ajaxMsg(1, "找不到该组织");
            }

            D('PartyOrganizationMs')->where(array('organization_id'=>$id))->delete();

            D('PartyOrganizationMs')->add(array('organization_id'=>$id,'uid'=>$ms_uid));
            D('PartyOrganization')->where(array('id'=>$id))->save($array);

        } else {

            $array['create_time'] = time();
            $id =  D('PartyOrganization')->add($array);
            D('PartyOrganizationMs')->add(array('organization_id'=>$id,'uid'=>$ms_uid));
        }


        ajaxMsg(0, '保存成功');
    }
//保存新增成员
    public function ajaxSaveMember()
    {
        $uid = intval(I('id'));
        $organization_id = intval(I('organization_id'));
        $status = intval(I('status',0));
        if(!$organization_id){
            ajaxMsg(1, '参数有误');
        }
        if (!$uid) {
            ajaxMsg(1, '请先选择用户');
        }
        //$status    0:成员 1:书记 2:副书记 3:管理员
        if($status == 1){
            D('PartyOrganizationMembers')->where(array('area_id'=>$organization_id,'status'=>1))->delete();//书记就一个，添加之前删除原来的
        }
        if($uid){
            $name =  D('user')->where("uid=$uid")->field('realname')->find();
            D('PartyOrganizationMembers')->add(array('organization_id'=>$organization_id,'uid'=>$uid,'status'=>$status,'realname'=>$name['realname']));
            ajaxMsg(0, '保存成功');
        }else{
            ajaxMsg(1, '参数错误');
        }


    }
//新增成员
    public function add_member()
    {
        $organization_id = I('organization_id');
        $Organization = D('PartyOrganization')->where("id=$organization_id")->find();
        //获取SetMembers表里设置好的成员角色可选项
        $org_members = D('SetMembers')->where(array('type'=>'org_status_id'))->find();
        $org_status_id =  explode(",",$org_members['status_id']);
        foreach ($org_status_id as $key =>$v){
            $post_data = D('PartyPost')->where(array('status_id'=>$v))->find();
            $set_org_members[$key]['value'] = $v;
            $set_org_members[$key]['name'] = $post_data['name'];
        }
        $this->assign('set_org_members', $set_org_members);
        $this->assign('Organization',$Organization);
        $this->assign('organization_id',$organization_id);
////        $this->assign('p', I('get.p', 1));
        $this->display();
    }
    public function ajaxSaveMemberold()
    {

        $id = I('id');
        $organization_id = I('organization_id');
        $adm_uid = I('adm_uid');
        $is_sj = I('is_sj',0);

        if(!$organization_id){
            ajaxMsg(1, '参数有误');
        }

        if (!$id) {
            ajaxMsg(1, '请先选择用户');
        }

        $detail = D('User')->find($id);
        if ($detail['organization_id'] && $detail['organization_id'] != $organization_id) {
            $dangzu = D('PartyOrganization')->find($detail['organization_id']);
            ajaxMsg(1, "该用户属于{$dangzu['name']}");
        }

        if($adm_uid){
            $sj =  D('PartyOrganizationAdm')->where(array('uid'=>$adm_uid))->find();
            if($sj && $sj['organization_uid'] != $id){
                $dangzu = D('PartyOrganization')->find($sj['organization_id']);
                $userO = D('User')->find($sj['organization_uid']);
                ajaxMsg(1,"该用户已担任{$dangzu['name']}-{$userO['realname']}的管理员");
            }
        }





        D('PartyOrganizationAdm')->where(array('organization_id'=>$organization_id,'organization_uid'=>$id))->delete();
        if($is_sj == 1){
            D('PartyOrganizationSj')->where(array('organization_id'=>$organization_id))->delete();
            D('PartyOrganizationSj')->add(array('organization_id'=>$organization_id,'uid'=>$id));
        }

        D('User')->where(array('uid'=>$id))->save(array('organization_id'=>$organization_id));
        if($adm_uid){
            D('PartyOrganizationAdm')->add(array('organization_id'=>$organization_id,'organization_uid'=>$id,'uid'=>$adm_uid));
        }


        ajaxMsg(0, '保存成功');
    }


}