<?php
namespace Admin\Controller;

use Admin\Model\AdminAuthRuleViewModel;
use Common\Controller\BaseController;
use Think\Controller;
use Admin\Util\AdminUtil;

/**
 * 群团组织
 * Class ContentController
 * @package Home\Controller
 */
class PartySocieyController extends BaseAdminController
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->set_sidebar_module('PartyBranch');
        $this->set_sidebar_sub('partySociey');
    }

    public function index()
    {

        $auth = session_auth();

        if($auth == 1){//总支
            $list =D('PartySociey')->order('name asc')->select();

            foreach($list as $index=>$item){
                $item['intro'] = str_replace(array("\r\n", "\r", "\n"),"<br>", $item['intro']);//换行替换显示
                $item['honors'] = str_replace(array("\r\n", "\r", "\n"),"<br>", $item['honors']);//换行替换显示
                $item['other_in_charge'] = str_replace(array("\r\n", "\r", "\n"),"<br>", $item['other_in_charge']);//换行替换显示
                $list[$index] = $item;
            }

            $this->assign('list', $list);
        }

        $this->display();
    }


    public function edit($id = 0)
    {
        if ($id > 0) {
            $condition['id'] = $id;
            $detail = D('PartySociey')->where($condition)->find();
            $this->assign('detail', $detail);

        }
        $this->display();
    }


    public function ajaxDec($id = 0){
        $auth = session_auth();
        if($auth == 1){
            D('PartySociey')->where(array('id'=>$id))->delete();
        }
        ajaxMsg(0, '删除成功');
    }

    #新增文章 ajax提交
    public function ajaxSave()
    {
        $id = I('id');
        $name = I('name');
        $main_in_charge = I('main_in_charge');
        $intro = $_POST['intro'];
        $honors = $_POST['honors'];
        $other_in_charge = $_POST['other_in_charge'];
        $people_count = I('people_count',0);
        if (!$name) {
            ajaxMsg(1, '请先填写党组名称');
        }

//ajaxMsg(1,to_json_string($_POST));
        $array = array(
            'name' => $name,
            'people_count'=>$people_count,
            'main_in_charge' => $main_in_charge,
        );
        $array['intro'] = $intro;//str_replace(array("\r\n", "\r", "\n"),"<br>", $intro);//换行替换显示
        $array['honors'] = $honors;//str_replace(array("\r\n", "\r", "\n"),"<br>", $honors);//换行替换显示
        $array['other_in_charge'] = $other_in_charge;str_replace(array("\r\n", "\r", "\n"),"<br>", $other_in_charge);//换行替换显示

        if ($id) {

            $detail = D('PartySociey')->find($id);
            if (!$detail) {
                ajaxMsg(1, "找不到该组织");
            }
            $auth = session_auth();
            if($auth == 1){

                D('PartySociey')->where(array('id' => $id))->save($array);
            }

        } else {

            $auth = session_auth();
            if($auth == 1){
                D('PartySociey')->add($array);

            }


        }


        ajaxMsg(0, '保存成功');
    }


public function alliance() {
		$this->set_sidebar_module('PartySociey');
        $type = I('type','labor');
		$this -> set_sidebar_sub($type);
		$keyword = I('keyword');
		$search['keyword'] = $keyword;
		if ($keyword) {
//			$map['AllianceArticle.title'] = array("like", "%$keyword%");
            $map['AllianceArticle.title'] = array("like", "%$keyword%");
            $this->assign('keyword', $keyword);
		}

		$map['AllianceArticle.status'] = array('gt', -1);
		$map['AllianceArticle.type'] = $type;

        $auth = AdminUtil::auth();
        // 支部管理员
        if($auth == 3) {
            $branch = AdminUtil::auth_branch();
            $map['AllianceArticle.branch_id'] = $branch['id'];
        }

		$page = D('AllianceArticleView') -> findPage($map, 15, 'AllianceArticle.is_top desc, AllianceArticle.create_time desc');
		$this -> assign('page', $page);
		$this -> assign('type', $type);
		$this -> display();
	}


    public function  ajaxChangeIsTop(){
        $id = I('id');
        $item = D('AllianceArticle')->find($id);
        if($item){
            $status = $item['is_top'];
            if($status == -1){
                ajaxMsg(1,'该信息已经删除了');
            }
            if($status == 1){
                $save['is_top'] = 0;
            }else{
                $save['is_top'] = 1;
            }
            D('AllianceArticle')->where(array('id'=>$id))->save($save);
            ajaxMsg(0,'保存成功');
        }else{
            ajaxMsg(1,'该活动已经删除了');
        }
    }

#新增文章 ajax提交
	public function ajaxSaveAlliance() {

		$id = I('id');
		$title = I('title');
		$type = I('type');
		$content = $_POST['editorValue'];
        $isTop =  I('is_top');
		$status = I('status', 1);
		if (!$title) {
			ajaxMsg(1, '请先填写标题');
		}
		$array = array('is_top'=>$isTop, 'title' => $title, 'content' => $content);
		if ($id) {
			
			$detail = D('AllianceArticle') -> where(array('id'=>$id))->save($array);
		} else{
            $auth = AdminUtil::auth();
             // 支部管理员
            if($auth == 3) {
            $branch = AdminUtil::auth_branch();
            $array['branch_id'] = $branch['id'];
            }
            $admin = AdminUtil::admin();
            $array['uid']=$admin['uid'];
			$array['create_time'] = time();
			$array['type']=$type;
			D('AllianceArticle') -> add($array);
		}

		ajaxMsg(0, '保存成功');
	}

    public function allianceEdit()
    {
    	$this->set_sidebar_module('PartySociey');
		$id = I('get.id');
		 $type = I('get.type','labor');
		 
		$this -> set_sidebar_sub($type);
        if ($id > 0) {
            $condition['id'] = $id;
            $detail = D('AllianceArticle')->where($condition)->find();
			$type = $detail['type'];
			
            $this->assign('detail', $detail);

        }
		$this -> assign('type', $type);
        $this->display();
    }

	public function ajaxDecAlliance() {
		$id = I('id');
		D('AllianceArticle') -> where(array('id' => $id)) -> save(array('status' => -1));
		ajaxMsg(0, '删除成功');
	}


}