<?php
namespace Admin\Controller;

use Think\Controller;

/**
 * 网页版登录
 * Class IndexController
 * @package Admin\Controller
 */
class QuestionnaireController extends BaseAdminController
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->set_sidebar_module('App');
        $this->set_sidebar_sub('Questionnaire');
    }

    public function ajaxChangeTextStatus()
    {
        $id = I('id');
        $item = D('QuestionnaireExam')->find($id);
        if ($item) {
            $status = $item['status'];
            if ($status == -1) {
                ajaxMsg(1, '该问卷已经删除了');
            }
            if ($status == 1) {
                $save['status'] = 0;
            } else {
                $save['status'] = 1;
                // 推送消息
                $this->pushQuestionnaire($id);
            }
            D('QuestionnaireExam')->where(array('id' => $id))->save($save);
            ajaxMsg(0, '保存成功');
        } else {
            ajaxMsg(1, '该问卷已经删除了');
        }
    }

    public function testEdit()
    {
        $id = I('id');
        if ($id) {
            $detail = D('QuestionnaireExamView')->where("QuestionnaireExam.id=$id and QuestionnaireExam.status>-1")->find();
            $roles = D('QuestionnaireExamRole')->where(array('exam_id' => $id))->select();
            $branch_id = $roles[0]['branch_id'];
            $detail['role_limit'] = $roles;
            $this->assign('detail', $detail);
            $this->assign('branch_id', $branch_id);
        }

        $branch_list = D('PartyBranch')->field('id,name')->select();
        $this->assign('branch_list', $branch_list);
        $roles = D('Role')->select();
        $this->assign('roles', $roles);

        $this->assign('p', I('p', 1));
        $this->display();
    }

    public function ajaxDelTest()
    {
        $id = I('id');
        D('QuestionnaireExam')->where(array('id' => $id))->save(array('status' => -1));
        ajaxMsg(0, '删除成功');

    }

    public function ajaxDoPublish($id)
    {

        $exam = D('QuestionnaireExam')->find($id);
        $this->_checkExamStatus($exam);


        $subjects = D('QuestionnaireExamSubjectView')->findAllByExam($exam);

        //判断能否自动改卷,如果全部是标题和选择题的话，标记为自动批改
        $autoCorrect = 0;
        foreach ($subjects as $subject) {
            $type_num = $subject['type_num'];
            if ($type_num == 'choice' || $type_num == 'singleChoice' || $type_num == 'text') {

            } else {
                $autoCorrect = 1;
                break;
            }
        }


        $exam['auto_correct'] = $autoCorrect;
        $exam['status'] = 1;
        $exam['update_time'] = time();
        $exam['publish_time'] = time();
        D('QuestionnaireExam')->save($exam);
        ajaxMsg(0, 'success');
    }


    #问卷列表
    public function index()
    {

        $admin = admin();
        $auth = session_auth();
        $map = array();
        if ($auth == 2) {//总支
            $map['QuestionnaireExam.branch_hq_id'] = $admin['admin_branch_hq_id'];
        }
        if ($auth == 3) {//支部
            $map['QuestionnaireExam.branch_id'] = $admin['admin_branch_id'];
        }

        $map['QuestionnaireExam.status'] = array('gt', -1);

        $keyword = I('keyword');
        if ($keyword) {
            $map['QuestionnaireExam.title'] = array('like', '%' . $keyword . '%');
            $this->assign('search', array('keyword' => $keyword));
        }



        $page = D('QuestionnaireExamView')->findPage($map, 15, 'QuestionnaireExam.create_time desc');
        foreach ($page['list'] as $index => $item) {
            $roles = D('QuestionnaireExamRoleView')->where(array('exam_id' => $item['id']))->select();
            $item['role_limit'] = $roles;
            $page['list'][$index] = $item;
        }
        $this->assign('page', $page);
        $this->display();
    }

    #发布取消发布问卷
    public function changeExam()
    {

        $id = $_GET['id'];
        $exam_model = M('QuestionnaireExam');
        $condition = 'uid=' . admin_uid() . ' and id=' . $id . ' and status > -1';
        $exam = $exam_model->where($condition)->find();
        if ($exam) {
            $examModel = D('QuestionnaireExam');
            if ($exam['status'] == 0) {
                $exam['status'] = 1;
            } elseif ($exam['status'] == 1) {
                $exam['status'] = 0;
            }
            $examModel->save($exam);
        } else {
        }
        $this->redirect('index', array('p' => $_GET['p']));


    }

    /**
     * 移除
     */
    public function ajaxRemoveSubject()
    {
        $id = I('id');
        $subject = D('QuestionnaireExamSubject')->find($id);

        //判断试卷状态能否操作
        $examModel = D('QuestionnaireExam');
        $examId = $subject['exam_id'];
        $exam = $examModel->find($examId);
        $this->_checkExamStatus($exam);

        if ($subject) {
            if ($subject['status'] == 0) {
                D('QuestionnaireExamSubject')->delete($id);
            } else {
                $subject['status'] = -1;
                D('QuestionnaireExamSubject')->save($subject);
            }
            if ($examId) {
                $exam = $examModel->removeSubjectId($exam, $subject);
                $examModel->save($exam);
            }
            ajaxMsg(0, 'success', $subject);
        } else {
            ajaxMsg(1, '抱歉，没有找到对应的题目');
        }
    }

    public function ajaxShowCorrectStatus($examId)
    {

        $examModel = D('QuestionnaireExam');
        $exam = $examModel->find($examId);
        if ($exam) {
            $status = $exam['show_correct_status'];

            if ($status == 1)
                $status = 0;
            elseif ($status == 0)
                $status = 1;
            $exam['show_correct_status'] = $status;
            $examModel->save($exam);
            ajaxMsg(0, '');
        } else {
            ajaxMsg(1, '抱歉，没有找到你的试卷');
        }
    }

    public function ajaxUpSubject()
    {
        $id = I('id');
        $subject = D('QuestionnaireExamSubject')->find($id);

        //判断试卷状态能否操作
        $examModel = D('QuestionnaireExam');
        $examId = $subject['exam_id'];
        $exam = $examModel->find($examId);
        $this->_checkExamStatus($exam);

        if ($subject) {
            $exam = $examModel->upSubjectId($exam, $subject);
            $examModel->save($exam);
            ajaxMsg(0, 'success', $subject);
        } else {
            ajaxMsg(1, '抱歉，没有找到对应的题目');
        }
    }

    public function ajaxDownSubject()
    {
        $id = I('id');
        $subject = D('QuestionnaireExamSubject')->find($id);

        //判断试卷状态能否操作
        $examModel = D('QuestionnaireExam');
        $examId = $subject['exam_id'];
        $exam = $examModel->find($examId);
        $this->_checkExamStatus($exam);

        if ($subject) {
            $exam = $examModel->downSubjectId($exam, $subject);
            $examModel->save($exam);
            ajaxMsg(0, 'success', $subject);
        } else {
            ajaxMsg(1, '抱歉，没有找到对应的题目');
        }
    }

    public function ajaxInsertSubject($type, $id, $exam_id = null, $is_add)
    {
        if ($is_add == 'false') {
            $subjectPre = D('QuestionnaireExamSubject')->find($id);
            $exam_id = $subjectPre['exam_id'];
        }


        $subjectType = D('QuestionnaireExamSubjectType')->where("type='$type'")->find();

        if ($exam_id && $subjectType) {
            $examModel = D('QuestionnaireExam');

            $exam = D('QuestionnaireExam')->find($exam_id);

            //判断试卷状态能否操作
            $this->_checkExamStatus($exam);

            $subject = array(
                'create_time' => time(),
                'update_time' => time(),
                'uid' => admin_uid() ? admin_uid() : 0,
                'type_id' => $subjectType['id'],
                'exam_id' => $exam_id,
            );

            //设置默认值
            if ($type == 'text') {//如果是简答题
                $subject['title'] = "";
            } elseif ($type == 'choice') {//如果是多选题
                $subject['score'] = 1;
                $subject['title'] = '';
                $subject['right_answer'] = '[1,0,0,0]';
                $subject['content'] = '["","","",""]';

                $subject['right_answer_str'] = "A";
            } elseif ($type == 'singleChoice') {//如果是单选题
                $subject['score'] = 1;
                $subject['title'] = '';
                $subject['right_answer'] = '[1,0,0,0]';
                $subject['content'] = '["","","",""]';

                $subject['right_answer_str'] = "A";
            } elseif ($type == 'trueFalse') {//如果是单选题
                $subject['score'] = 1;
                $subject['title'] = '';
                $subject['right_answer'] = '[1,0]';
                $subject['content'] = '["正确","错误"]';

                $subject['right_answer_str'] = "正确";
            } elseif ($type == 'blank') {//如果是填空题
                $subject['score'] = 1;
                $subject['content'] = "";
                $subject['show_content'] = "";
                $subject['answer_count'] = 0;
            } elseif ($type == 'answer') {//如果是简答题
                $subject['score'] = 1;
                $subject['content'] = "";
                $subject['show_content'] = "";
            }
            $subject['remark'] = '';
            $subject['type_num'] = $type;
            //添加题目
            $id2 = D('QuestionnaireExamSubject')->add($subject);

            //考试添加题目id上去
            $subject['id'] = $id2;

            if ($subject) {
                if ($is_add == 'false') {//如果是插入
                    $exam = $examModel->insertSubjectId($exam, $id, $subject);
                    $examModel->save($exam);
                } else {//添加
                    $exam = $examModel->addSubjectId($exam, $subject);
                    $examModel->save($exam);
                }
            }

            ajaxMsg(0, 'success', $subject);
        } else {
            ajaxMsg(1, '抱歉，没有找到对应的创建类型');
        }
    }

    //已经抛弃了不用了
    public function ajaxAddSubject($type, $examId, $copyId = null)
    {
        $subjectType = D('QuestionnaireExamSubjectType')->findByType($type);
        if ($subjectType) {
            $examModel = D('QuestionnaireExam');
            $exam = $examModel->find($examId);
            //判断试卷状态能否操作
            $this->_checkExamStatus($exam);

            $subject = array(
                'create_time' => time(),
                'update_time' => time(),
                'uid' => admin_uid() ? admin_uid() : 0,
                'type_id' => $subjectType['id'],
                'exam_id' => $examId,
                'copy_id' => $copyId
            );
            //设置默认值
            if ($type == 'text') {//如果是简答题
                $subject['title'] = "标题内容";
            } elseif ($type == 'choice') {//如果是多选题
                $subject['score'] = 1;
                $subject['title'] = '填写多选题问题';
                $subject['right_answer'] = '[1,0,0,0]';
                $subject['content'] = '["填写答案A","填写答案B","填写答案C","填写答案D"]';
            } elseif ($type == 'singleChoice') {//如果是单选题
                $subject['score'] = 1;
                $subject['title'] = '填写多选题问题';
                $subject['right_answer'] = '[1,0,0,0]';
                $subject['content'] = '["填写答案A","填写答案B","填写答案C","填写答案D"]';
            } elseif ($type == 'blank') {//如果是填空题
                $subject['score'] = 1;
                $subject['content'] = "填空题内容";
            } elseif ($type == 'answer') {//如果是简答题
                $subject['score'] = 1;
                $subject['content'] = "简答题内容";
            }

            //添加题目
            $id = D('QuestionnaireExamSubject')->add($subject);

            //考试添加题目id上去
            $subject['id'] = $id;
            $exam = $examModel->addSubjectId($exam, $subject);
            $examModel->save($exam);

            ajaxMsg(0, 'success', array('id' => $id, 'type' => $type));
        } else {
            ajaxMsg(1, '抱歉，没有找到对应的创建类型');
        }
    }

    public function ajaxEditText($id, $title)
    {
        $subject = D('QuestionnaireExamSubjectView')->find($id);

        //判断试卷状态能否操作
        $examModel = D('QuestionnaireExam');
        $examId = $subject['exam_id'];
        $exam = $examModel->find($examId);
        $this->_checkExamStatus($exam);

        if ($subject) {
            $subjectModel = D('QuestionnaireExamSubject');
            $temp = $subjectModel->create($_POST);
            if ($temp) {
                $subject['status'] = 1;
                $subject['title'] = $title;
                $subject['remark'] = $_POST['remark'];
                $subject['update_time'] = time();
                D('QuestionnaireExamSubject')->save($subject);

                if ($exam) {
                    $exam = $examModel->changeSubject($exam, $subject);
                    $examModel->save($exam);
                }


                ajaxMsg(0, 'success', $subject);
            } else {
                ajaxMsg(1, $subjectModel->getError());
            }
        } else {
            ajaxMsg(1, '抱歉，没有找到对应的题目');
        }
    }

    public function ajaxEditSingle($id, $title, $score = 0, $is_answer, $choice)
    {

        if ((int)$is_answer > 3 || (int)$is_answer < 0) {
            ajaxMsg(1, '请提交正确格式的内容');
        }

        $subject = D('QuestionnaireExamSubjectView')->find($id);

        //判断试卷状态能否操作
        $examModel = D('QuestionnaireExam');
        $examId = $subject['exam_id'];
        $exam = $examModel->find($examId);
        $this->_checkExamStatus($exam);

        $right_answer = array(0, 0, 0, 0);
        $right_answer[(int)$is_answer] = 1;

        if ($subject) {

            $subjectModel = D('QuestionnaireExamSubject');
            $temp = $subjectModel->create($_POST);
            if ($temp) {
                $subject['status'] = 1;
                $subject['title'] = $title;
                $subject['score'] = (int)$score > 0 ? (int)$score : 1;
                $subject['content'] = json_encode($choice, true);
                $subject['remark'] = $_POST['remark'];
                $subject['right_answer'] = json_encode($right_answer, true);
                $subject['update_time'] = time();
                D('QuestionnaireExamSubject')->save($subject);


                if ($exam) {
                    $exam = $examModel->changeSubject($exam, $subject);
                    $examModel->save($exam);
                }

                $right_answerStr = array('A', 'B', 'C', 'D');
                $subject['right_answer_str'] = $right_answerStr[(int)$is_answer];
                ajaxMsg(0, 'success', $subject);
            } else {
                ajaxMsg(1, $subjectModel->getError());
            }

        } else {
            ajaxMsg(1, '抱歉，没有找到对应的题目');
        }
    }
    public function ajaxEditTrueFalse($id, $title, $score = 0, $is_answer, $choice)
    {

        if ((int)$is_answer > 1 || (int)$is_answer < 0) {
            ajaxMsg(1, '请提交正确格式的内容');
        }


        $subject = D('QuestionnaireExamSubjectView')->find($id);

        //判断试卷状态能否操作
        $examModel = D('QuestionnaireExam');
        $examId = $subject['exam_id'];
        $exam = $examModel->find($examId);
        $this->_checkExamStatus($exam);

        $right_answer = array(0, 0);
        $right_answer[(int)$is_answer] = 1;

        if ($subject) {

            $subjectModel = D('QuestionnaireExamSubject');
            $temp = $subjectModel->create($_POST);
            if ($temp) {
                $subject['status'] = 1;
                $subject['title'] = $title;
                $subject['score'] = (int)$score > 0 ? (int)$score : 1;
                $subject['content'] = json_encode($choice, true);
                $subject['remark'] = $_POST['remark'];
                $subject['right_answer'] = json_encode($right_answer, true);
                $subject['update_time'] = time();
                D('QuestionnaireExamSubject')->save($subject);


                if ($exam) {
                    $exam = $examModel->changeSubject($exam, $subject);
                    $examModel->save($exam);
                }

                $right_answerStr = array('正确', '错误');
                $subject['right_answer_str'] = $right_answerStr[(int)$is_answer];
                ajaxMsg(0, 'success', $subject);
            } else {
                ajaxMsg(1, $subjectModel->getError());
            }

        } else {
            ajaxMsg(1, '抱歉，没有找到对应的题目');
        }
    }

    public function ajaxEditChoice()
    {
        $id = I('id');
        $title = $_POST['title'];
        $score = I('score');
        $choice = I('choice');
        $answer = I('is_answer');
        if ($answer) {
            $len = sizeof($answer);
        } else {
            $len = 0;
        }

        if ($len == 0) {
            ajaxMsg(1, "请至少选择一个正确答案");
        }
        $subject = D('QuestionnaireExamSubjectView')->find($id);

        $right_answer = array(0, 0, 0, 0);
        foreach ($answer as $index) {
            $right_answer[$index] = 1;
        }

        //判断试卷状态能否操作
        $examModel = D('QuestionnaireExam');
        $examId = $subject['exam_id'];
        $exam = $examModel->find($examId);
        $this->_checkExamStatus($exam);

        if ($subject) {
            $subject['status'] = 1;
            $subject['title'] = $title;
            $subject['remark'] = $_POST['remark'];
            $subject['score'] = $score;
            $subject['content'] = json_encode($choice, true);
            $subject['right_answer'] = json_encode($right_answer, true);
            $subject['update_time'] = time();
            D('QuestionnaireExamSubject')->save($subject);


            if ($exam) {
                $exam = $examModel->changeSubject($exam, $subject);
                $examModel->save($exam);
            }

            $right_answerStr = array('A', 'B', 'C', 'D');
            $show = "";
            foreach ($answer as $index => $value) {
                if ($index < $len - 1) {
                    $show = $show . $right_answerStr[$value] . '、';
                } else {
                    $show = $show . $right_answerStr[$value];
                }
            }

            $subject['right_answer_str'] = $show;
            ajaxMsg(0, 'success', $subject);
        } else {
            ajaxMsg(1, '抱歉，没有找到对应的题目');
        }
    }

    public function ajaxEditBlank()
    {
        $id = $_POST['id'];
        $score = $_POST['score'];
        $answer = $_POST['answer'];
        $content = $_POST['content'];
//        $answer = htmlspecialchars_decode($answer);


        //判断是否有空的答案
        $len = 1;
        $objA = json_decode($answer, JSON_UNESCAPED_UNICODE);
        if ($objA) {
            foreach ($objA as $oo) {
                if ($oo == "") {
                    $len = 0;
                }
            }
        } else {
            $len = 0;
        }

        if ($len == 0) {
            ajaxMsg(1, "所有填空必须填写答案并保证至少有一个填空");
        }
        $subject = D('QuestionnaireExamSubjectView')->find($id);


        //判断试卷状态能否操作
        $examModel = D('QuestionnaireExam');
        $examId = $subject['exam_id'];
        $exam = $examModel->find($examId);
        $this->_checkExamStatus($exam);

        if ($subject) {
            $subject['status'] = 1;
            $subject['remark'] = $_POST['remark'];
            $subject['score'] = $score;
            $subject['content'] = $content;
            $subject['right_answer'] = $answer;
            $subject['update_time'] = time();
            D('QuestionnaireExamSubject')->save($subject);

            if ($exam) {
                $exam = $examModel->changeSubject($exam, $subject);
                $examModel->save($exam);
            }

            $answerCount = substr_count($content, 'input-blank');
            $subject['answer_count'] = $answerCount;
//            $subject['content'] = htmlspecialchars_decode($subject['content']);

            $subject = $this->_getShoBlank($subject);
            ajaxMsg(0, 'success', $subject);
        } else {
            ajaxMsg(1, '抱歉，没有找到对应的题目');
        }
    }

    public function ajaxEditAnswer($id, $score, $content)
    {

        $subject = D('QuestionnaireExamSubjectView')->find($id);

        //判断试卷状态能否操作
        $examModel = D('QuestionnaireExam');
        $examId = $subject['exam_id'];
        $exam = $examModel->find($examId);
        $this->_checkExamStatus($exam);

        if ($subject) {

            $subjectModel = D('QuestionnaireExamSubject');
            $temp = $subjectModel->create($_POST);
            if ($temp) {
                $subject['status'] = 1;
                $subject['score'] = $score;
                $subject['remark'] = $_POST['remark'];
                $subject['content'] = $content;
                $subject['update_time'] = time();
                D('QuestionnaireExamSubject')->save($subject);


                if ($exam) {
                    $exam = $examModel->changeSubject($exam, $subject);
                    $examModel->save($exam);
                }

                $subject['content'] = htmlspecialchars_decode($subject['content']);
                ajaxMsg(0, 'success', $subject);
            } else {
                ajaxMsg(1, $subjectModel->getError());
            }

        } else {
            ajaxMsg(1, '抱歉，没有找到对应的题目');
        }
    }

    public function ajaxFinishCorrect($examPaperId)
    {

        $examPaperModel = D('QuestionnaireExamPaper');
        $examPaper = $examPaperModel->find($examPaperId);

        if ($examPaper) {
            $exam = D('QuestionnaireExam')->find($examPaper['exam_id']);
            $this->_checkExamStatus($exam);//检测权限


            if ($examPaper['is_corrected'] == 0) {//当第一题提交批改
                //将题目得分统计如每道题里
                $scores = $examPaperModel->getScores($examPaper);
                $subjectMode = D('QuestionnaireExamSubject');
                foreach ($scores as $subjectId => $score) {
                    $subject = $subjectMode->find((int)$subjectId);
                    if ($subject) {
                        if ($score > 0) {
                            $subject['answer_right_count'] = $subject['answer_right'] + 1;
                            $subject['answer_score'] = $subject['answer_score'] + $score;
                        }
                        $subject['answer_count'] = $subject['answer_count'] + 1;
                        $subjectMode->save($subject);
                    }

                }
            }

            //消息生成
            $messageFun = $examPaper['status'] ? 'exam_re_correct_message' : 'exam_correct_message';
            D("Message/Message")->$messageFun(admin_uid(), $examPaper['uid'], $examPaper['exam_id']);


            //改变对应题目的分数并重新计算试卷分数
            $examPaper['is_corrected'] = 1;
            $examPaperModel->save($examPaper);

//            $examPaperModel = D('QuestionnaireExamPaperView');
//                $paper = $examPaperModel->findNext($examPaper['exam_id']);
            ajaxMsg(0, 'success');
//            $paper = $examPaperModel->findNextByPaperId($examPaper['exam_id'], $examPaperId);
//            if ($paper) {
//                ajaxMsg(0, 'success');
//            } else {
//                ajaxMsg(1, '您已经批改完所有参考者的试卷了');
//            }


        } else {
            ajaxMsg(1, '抱歉你操作的试卷走丢了');
        }
    }

    public function ajaxGetLastPaper($examPaperId)
    {


        $examPaperModel = D('QuestionnaireExamPaperView');
        $examPaper = $examPaperModel->find($examPaperId);
        if ($examPaper) {
            $paper = $examPaperModel->findLastByPaperId($examPaper['exam_id'], $examPaperId);
            if ($paper) {
                ajaxMsg(0, 'success');
            } else {
                ajaxMsg(1, '没有上一份了');
            }


        } else {
            ajaxMsg(1, '抱歉你操作的试卷走丢了');
        }
    }

    /**
     * @param $examPaperId
     * @param $subjectId
     * @param  $score [0,1,2] 数组方式
     */
    public function ajaxDoCorrect($examPaperId, $subjectId, $score = array(0))
    {
//        ajaxMsg(1, to_json_string($_POST));
        $examPaperModel = D('QuestionnaireExamPaper');
        $examPaper = $examPaperModel->find($examPaperId);
        if ($examPaper) {
            $exam = D('QuestionnaireExam')->find($examPaper['exam_id']);
            $this->_checkExamStatus($exam);//检测权限

            //计算每题得分
            if ($examPaper['is_corrected'] == 1) {//当已经批改过了
                $scores = $examPaperModel->getScores($examPaper);
                $subjectMode = D('QuestionnaireExamSubject');
                $subject = $subjectMode->find((int)$subjectId);
                if ($subject) {
                    $oldScore = $scores[$subjectId . ''] ? $scores[$subjectId . ''] : 0;

                    $suScore = 0;
                    if (is_array($score)) {
                        foreach ($score as $s) {
                            $suScore = $suScore + $s;
                        }
                    } else {
                        $suScore = $score;
                    }
//                    ajaxMsg(1,to_json_string($scores));
                    if ($oldScore != $suScore) {
                        if ($oldScore > 0) {//还原原来分数
                            $subject['answer_right_count'] = $subject['answer_right'] - 1;
                            $subject['answer_score'] = $subject['answer_score'] - $oldScore;
                        }

                        if ($suScore > 0) {
                            $subject['answer_right_count'] = $subject['answer_right'] + 1;
                            $subject['answer_score'] = $subject['answer_score'] + $suScore;
                        }
                        $subjectMode->save($subject);
                    }
                }

            }

            //改变对应题目的分数并重新计算试卷分数
            $examPaper = $examPaperModel->changeScore($examPaper, $subjectId, $score);

            $examPaperModel->save($examPaper);
            ajaxMsg(0, 'success', $examPaper['exam_score']);
        } else {
            ajaxMsg(1, '抱歉你操作的试卷走丢了');
        }
    }

    public function correct($correctType, $examId = 0)
    {
        $entryType = I("entryType", "correct");
        $paperId = I('examPaperId', 0);
        $examPaperModel = D('QuestionnaireExamPaperView');
        if ($correctType == 'last') {
            if ($paperId != 0) {
                $paper = $examPaperModel->findLastByPaperId($examId, $paperId);

                $paper2 = $examPaperModel->findLastByPaper($examId, $paper);
                if ($paper2) {
                    $this->assign('hasLast', true);
                }
            } else {
                $paper = $examPaperModel->findNext($examId);
                $paper2 = $examPaperModel->findLastByPaper($examId, $paper);
                if ($paper2) {
                    $this->assign('hasLast', true);
                }
            }
            if ($paper) {
                $examId = $paper['exam_id'];
                $paper3 = $examPaperModel->findNextByPaper($examId, $paper);
                if ($paper3) {
                    $this->assign('hasNext', true);
                }
            } else {
                $this->assign('finishCorrect', '您已经批改完所有参考者的试卷了');
            }

        } elseif ($correctType == 'next') {
            if ($paperId != 0) {
                $paper = $examPaperModel->findNextByPaperId($examId, $paperId);

                $paper2 = $examPaperModel->findNextByPaper($examId, $paper);
                if ($paper2) {
                    $this->assign('hasNext', true);
                }
            } else {
                $paper = $examPaperModel->findNext($examId);

                if (!$paper) {
                    $exam = D('QuestionnaireExamView')->find($examId);
                    $this->assign('exam', $exam);
                    $this->assign('entryType', $entryType);
                    $this->assign('is_show', false);
                    $this->assign('show_title', '抱歉，该试卷无人答题，暂无答卷批改。');
                    $this->display();
                    exit;
                }

                $paper2 = $examPaperModel->findNextByPaper($examId, $paper);
                if ($paper2) {
                    $this->assign('hasNext', true);
                }
            }


            if ($paper) {
                $examId = $paper['exam_id'];
                $paper3 = $examPaperModel->findLastByPaper($examId, $paper);
                if ($paper3) {
                    $this->assign('hasLast', true);
                }
            } else {

                $this->assign('finishCorrect', '您已经批改完所有参考者的试卷了');
            }

        } else if ($correctType == 'correct') {
            $paper = $examPaperModel->findById($paperId);
            $examId = $paper['exam_id'];
            $paper2 = $examPaperModel->findLastByPaper($examId, $paper);
            if ($paper2) {
                $this->assign('hasLast', true);
            }

            $paper3 = $examPaperModel->findNextByPaper($examId, $paper);
            if ($paper3) {
                $this->assign('hasNext', true);
            }
        }
        $exam = D('QuestionnaireExamView')->find($examId);
        $this->assign('exam', $exam);
        $this->assign('entryType', $entryType);

        if ($paper) {//如果试卷存在

            $this->_checkExamStatusPage($exam, 'correct');//检测权限

            $subjects = D('QuestionnaireExamSubjectView')->findAllByExam($exam);

            $userScore = to_json_obj($paper['answer_scores']);
            $userAnswer = to_json_obj($paper['answers']);


            foreach ($subjects as $index => $subject) {
                /***********放入用户答案**********/
                $subject['user_score'] = $userScore['' . $subject['id']];
                $subject['user_answer'] = $userAnswer['' . $subject['id']];

                /***********放入原题内容**********/
                if ($subject['type_num'] == 'choice') {//如果是多选题

                    //用户回答
                    $userA = array(0, 0, 0, 0);
                    foreach ($userAnswer['' . $subject['id']] as $select) {
                        $userA[(int)$select] = 1;
                    }
                    $subject['user_answer'] = $userA;

                    //解析显示的正确答案(A、B、C)
                    $right_answerStr = array('A', 'B', 'C', 'D');
                    $show = "";
                    $answer = json_decode($subject['right_answer']);
                    $right_answerS = array();
                    $righr_answer_indexs = array();
                    foreach ($answer as $index2 => $value) {
                        if ($value == 1) {
                            $righr_answer_indexs[(string)$index2] = 1;
                            array_push($right_answerS, $right_answerStr[$index2]);
                        }
                    }
                    $len = sizeof($right_answerS);
                    foreach ($right_answerS as $index2 => $s) {
                        if ($index2 < $len - 1) {
                            $show = $show . $s . '、';
                        } else {
                            $show = $show . $s;
                        }
                    }
                    $subject['right_answer_str'] = $show;
                    $subject['righr_answer_indexs'] = $righr_answer_indexs;

                    //解析答案内容
                    $subject['answer'] = json_decode($subject['content'], true);
                } elseif ($subject['type_num'] == 'singleChoice') {//如果是单选题

                    //用户回答
                    $subject['user_answer'] = $userAnswer['' . $subject['id']];

                    //解析显示正确答案(A)
                    $right_answerStr = array('A', 'B', 'C', 'D');
                    $answer = json_decode($subject['right_answer'], true);
                    $righr_answer_indexs = array();
                    foreach ($answer as $index2 => $value) {
                        if ($value == 1) {
                            $righr_answer_indexs[(string)$index2] = 1;
                            $show = $right_answerStr[$index2];
                        }
                    }
                    $subject['right_answer_str'] = $show;
                    $subject['righr_answer_indexs'] = $righr_answer_indexs;

                    //解析答案内容
                    $subject['answer'] = json_decode($subject['content'], true);
                } elseif ($subject['type_num'] == 'blank') {//如果是填空题

                    //用户回答
                    $subject['user_answer'] = $userAnswer['' . $subject['id']];

                    //解析html 转义字符
                    $answerCount = substr_count($subject['content'], 'input-blank');
                    $subject['answer_count'] = $answerCount;
                    $subject['content'] = $subject['content'] ? htmlspecialchars_decode($subject['content']) : "";

                    $answer = to_json_obj($subject['right_answer']);
                    $righA = "";
                    $userAnswerS = "";
                    $showContent = $subject['content'];
                    foreach ($answer as $index2 => $value) {
                        $ua = $subject['user_answer'][$index2];
                        if (!$ua) {
                            $ua = "&nbsp;&nbsp;";
                        }
                        $showContent = str_replace("value=\"" . $value . "\"", "value=\"" . $ua . "\" style=\"display:none\"", $showContent);
                        $userAnswerS = $userAnswerS . "<span style='padding: 0 10px;border-bottom: 1px solid black;margin-left: 10px;margin-right: 10px'>" . $ua . "</span>";
                        $righA = $righA . '<span style="display:block">' . ($index2 + 1) . '.' . $value . "</span>";
                        $subject['content'] = str_replace("value=\"" . $value . "\"", "value=\"" . $ua . "\"", $subject['content']);

                        $righA = $righA . '<span style="display:block">' . ($index2 + 1) . '.' . $value . "</span>";
                    }
                    $subject['show_content'] = str_replace_once("<input class=", $userAnswerS . "<input class=", $showContent);


                    $subject['right_answer_str'] = $righA;


                } elseif ($subject['type_num'] == 'answer') {//如果是简答题
                    //解析html 转义字符
                    $subject['content'] = $subject['content'] ? htmlspecialchars_decode($subject['content']) : "";
                    $subject['user_answer'][0] = $subject['user_answer'][0] ? htmlspecialchars_decode($subject['user_answer'][0]) : "";
                }

                //重新赋值
                $subjects[(int)$index] = $subject;
            }


            $this->assign('examPaper', $paper);
            $this->assign('subjects', $subjects);

            $showname = show_name($paper, 'user_');
            $this->setTitle("批改 " . $showname . ' 的问卷');

        } else {
            $this->assign('entryType', $entryType);
            $this->assign('is_show', false);
            $this->assign('show_title', '抱歉，没有找到你要批改的试卷');
        }
        $this->display();
    }


    #新增问卷
    public function ajaxSaveTest()
    {
        $id = I('id');
        $title = I('title');
        $status = I('status', 0);
        $end_time = I('end_time');
        $role_limit = I('role_limit');
        $type = I('type', 1);
        $branch_id = I('branch_id')?I('branch_id'):0;
        $_USER = M('User');
        if (!$title) {
            ajaxMsg(1, "请先填写标题");
        }
        if (!$end_time) {
            ajaxMsg(1, "请选择结束日期");
        }
        if (!$role_limit) {
            ajaxMsg(1, '查看限制至少选择1个');
        }

        $sizeRole = sizeof($role_limit);
        if ($sizeRole < 1) {
            ajaxMsg(1, '查看限制至少选择1个');
        }
        $array = array(
            'type' => $type,
            'title' => $title,
            'intro' => I('intro'),
            'end_time' => strtotime($end_time),
        );
        if ($id) {
            $item = D('QuestionnaireExam')->find($id);
            $oldStatus = $item['status'];
            if ($oldStatus < 0) {
                ajaxMsg(1, '该活动已经删除了');
            }
            $array['update_time'] = time();
            $array['status'] = $status;

            //统计需要调查总人数
            $mumber_count = 0;
            if ($role_limit) {
                foreach ($role_limit as $v) {
                    $temp = $_USER->where(array('role_id' => $v))->count();
                    $mumber_count += $temp;
                }
            }
            $array['exam_total_count'] = $mumber_count;
            // 如果保存并且结束时间为真时主动推送
            if ( $status && ($array['end_time'] > time()) ) {
                // 推送消息
                $this->pushQuestionnaire($id);

            }
            D('QuestionnaireExam')->where(array('id' => $id))->save($array);
            D('QuestionnaireExamRole')->where(array('exam_id' => $id))->delete();
            foreach ($role_limit as $item) {
                D('QuestionnaireExamRole')->add(array('exam_id' => $id, 'role_id' => $item,'branch_id'=>$branch_id));
            }
            ajaxMsg(0, '保存成功');
        } else {
            $array['uid'] = admin_uid();
            $array['status'] = $status;
            $array['update_time'] = time();
            $array['create_time'] = time();
            $array = set_save_auth($array);
            $id = D('QuestionnaireExam')->add($array);
            foreach ($role_limit as $item) {
                D('QuestionnaireExamRole')->add(array('exam_id' => $id, 'role_id' => $item,'branch_id'=>$branch_id));
            }
            ajaxMsg(0, '保存成功');
        }

    }


    #答题名单
    public function manage()
    {
        $exam_id = I('id');
        $exam = D('QuestionnaireExam')->where(array('id' => $exam_id))->find();

        if ($exam) {
            //题目ids
            $ids = implode(",", to_json_obj($exam['subject_ids']));
            if ($ids) {
                $subjects = D('QuestionnaireExamSubjectView')->where("QuestionnaireExamSubject.id in($ids)")->order("field(QuestionnaireExamSubject.id, $ids)")->select();
            }

            $this->assign('detail', $exam);

            $this->assign('list', $subjects);
            $this->setTitle("问卷管理");
        }
        $this->assign('p', I('p', 1));
        $this->display();
    }


    #答题名单
    public function analysis()
    {
        $exam_id = $_GET[id];
        $exam_model = M('QuestionnaireExam');
        $exam = $exam_model->where(array('id' => $exam_id))->find();
        if ($exam) {
            $page = D('QuestionnaireExamPaperView')->findMyPageByUid($exam_id);

            //统计已批改的平均分
            $avgScore = D('QuestionnaireExamPaper')->where(array('exam_id' => $exam_id, 'is_corrected' => 1))->avg('exam_score');
            $exam['avg_score'] = $avgScore;
            //统计及格人数
            $passScore = $exam['score'] * 0.6;
            $passCount = D('QuestionnaireExamPaper')->where(
                array('exam_id' => $exam_id, 'exam_score' => array('egt', $passScore), 'is_corrected' => 1)
            )->count();
            $exam['pass_count'] = $passCount;
            //统计已经批改
            $exam['corrected_count'] = D('QuestionnaireExamPaper')->where(
                array('exam_id' => $exam_id, 'is_corrected' => 1)
            )->count();
            //统计优秀人数
            $goodScore = $exam['score'] * 0.8;
            $goodCount = D('QuestionnaireExamPaper')->where(
                array('exam_id' => $exam_id, 'exam_score' => array('egt', $goodScore), 'is_corrected' => 1)
            )->count();
            $exam['good_count'] = $goodCount;
            $this->assign('exam', $exam);

            $subjects = D('QuestionnaireExamSubjectView')->findAllByExam($exam);

            foreach ($subjects as $index => $subject) {
                if ($subject['type_num'] == 'choice') {//如果是多选题

                    //解析显示的正确答案(A、B、C)
                    $right_answerStr = array('A', 'B', 'C', 'D');
                    $show = "";
                    $answer = json_decode($subject['right_answer']);
                    $right_answerS = array();
                    foreach ($answer as $index2 => $value) {
                        if ($value == 1) {
                            array_push($right_answerS, $right_answerStr[$index2]);

                        }
                    }
                    $len = sizeof($right_answerS);
                    foreach ($right_answerS as $index2 => $s) {
                        if ($index2 < $len - 1) {
                            $show = $show . $s . '、';
                        } else {
                            $show = $show . $s;
                        }
                    }
                    $subject['right_answer_str'] = $show;

                    //解析答案内容
                    $subject['answer'] = json_decode($subject['content'], true);
                } elseif ($subject['type_num'] == 'singleChoice') {//如果是单选题
                    //解析显示正确答案(A)
                    $right_answerStr = array('A', 'B', 'C', 'D');
                    $answer = json_decode($subject['right_answer'], true);
                    foreach ($answer as $index2 => $value) {
                        if ($value == 1) {
                            $show = $right_answerStr[$index2];
                        }
                    }
                    $subject['right_answer_str'] = $show;
                    //解析答案内容
                    $subject['answer'] = json_decode($subject['content'], true);
                } elseif ($subject['type_num'] == 'blank') {//如果是填空题
                    //解析html 转义字符
                    $answerCount = substr_count($subject['content'], 'input-blank');
                    $subject['answer_count'] = $answerCount;
                    $subject['content'] = $subject['content'] ? htmlspecialchars_decode($subject['content']) : "";

                    //替换显示
//                $userAnswerS = "";
//                $showContent = $subject['content'];
//                foreach (to_json_obj($subject['right_answer']) as $index2 => $value) {
//                    if(!$value){
//                        $value = "&nbsp;&nbsp;";
//                    }
//                    $showContent = str_replace("value=\"".$value."\"", "value=\"".$value."\" style=\"display:none\"", $showContent);
//                    $userAnswerS = $userAnswerS."<span style='padding: 0 10px;border-bottom: 1px solid black;margin-left: 10px;margin-right: 10px'>".$value."</span>";
//
//                }
                    $subject = $this->_getShoBlank($subject);//['show_content'] = str_replace_once("<input class=", $userAnswerS."<input class=", $showContent);


                } elseif ($subject['type_num'] == 'answer') {//如果是简答题
                    //解析html 转义字符
                    $subject['content'] = $subject['content'] ? htmlspecialchars_decode($subject['content']) : "";

                }
//重新赋值
                $subjects[(int)$index] = $subject;
            }


            $this->assign('subjects', $subjects);

            $this->assign('page', $page);
            $this->setTitle("问卷管理");
        }
        $this->display();
    }


    public function subjectManage($id)
    {
        $exam = D('QuestionnaireExamView')->find($id);
        $this->assign('detail', $exam);
        $this->assign('p', I('p', 1));
        $this->display();
    }


    /*****
     * 问卷编辑发布页面
     * @param $id
     */
    public function subjectEdit($id)
    {
        $exam = D('QuestionnaireExamView')->find($id);

        $this->_checkExamStatusPage($exam, 'publish');

//        if ($exam['ststus'] == 1) {//发布状态下 会将状态改为编辑状态
//            $exam['ststus'] = 0;
//            D('QuestionnaireExam')->save($exam);
//        }

        $this->assign('detail', $exam);
        $subjects = D('QuestionnaireExamSubjectView')->findAllByExam($exam);

        foreach ($subjects as $index => $subject) {
            if ($subject['type_num'] == 'choice') {//如果是多选题

                //解析显示的正确答案(A、B、C)
                $right_answerStr = array('A', 'B', 'C', 'D');
                $show = "";
                $answer = json_decode($subject['right_answer']);
                $right_answerS = array();
                foreach ($answer as $index2 => $value) {
                    if ($value == 1) {
                        array_push($right_answerS, $right_answerStr[$index2]);

                    }
                }
                $len = sizeof($right_answerS);
                foreach ($right_answerS as $index2 => $s) {
                    if ($index2 < $len - 1) {
                        $show = $show . $s . '、';
                    } else {
                        $show = $show . $s;
                    }
                }
                $subject['right_answer_str'] = $show;

                //解析答案内容
                $subject['answer'] = json_decode($subject['content'], true);
            } elseif ($subject['type_num'] == 'singleChoice') {//如果是单选题
                //解析显示正确答案(A)
                $right_answerStr = array('A', 'B', 'C', 'D');
                $answer = json_decode($subject['right_answer'], true);
                foreach ($answer as $index2 => $value) {
                    if ($value == 1) {
                        $show = $right_answerStr[$index2];
                    }
                }
                $subject['right_answer_str'] = $show;
                //解析答案内容
                $subject['answer'] = json_decode($subject['content'], true);
            } elseif ($subject['type_num'] == 'trueFalse') {//如果是单选题
                //解析显示正确答案(A)
                $right_answerStr = array('正确', '错误');
                $answer = json_decode($subject['right_answer'], true);
                foreach ($answer as $index2 => $value) {
                    if ($value == 1) {
                        $show = $right_answerStr[$index2];
                    }
                }
                $subject['right_answer_str'] = $show;
                //解析答案内容
                $subject['answer'] = json_decode($subject['content'], true);
            } elseif ($subject['type_num'] == 'blank') {//如果是填空题
                //解析html 转义字符
                $answerCount = substr_count($subject['content'], 'input-blank');
                $subject['answer_count'] = $answerCount;
                $subject['content'] = $subject['content'] ? htmlspecialchars_decode($subject['content']) : "";

                //替换显示
//                $userAnswerS = "";
//                $showContent = $subject['content'];
//                foreach (to_json_obj($subject['right_answer']) as $index2 => $value) {
//                    if(!$value){
//                        $value = "&nbsp;&nbsp;";
//                    }
//                    $showContent = str_replace("value=\"".$value."\"", "value=\"".$value."\" style=\"display:none\"", $showContent);
//                    $userAnswerS = $userAnswerS."<span style='padding: 0 10px;border-bottom: 1px solid black;margin-left: 10px;margin-right: 10px'>".$value."</span>";
//
//                }
                $subject = $this->_getShoBlank($subject);//['show_content'] = str_replace_once("<input class=", $userAnswerS."<input class=", $showContent);


            } elseif ($subject['type_num'] == 'answer') {//如果是简答题
                //解析html 转义字符
                $subject['content'] = $subject['content'] ? htmlspecialchars_decode($subject['content']) : "";

            }
//重新赋值
            $subjects[(int)$index] = $subject;
        }

        $this->assign('subjects', $subjects);

        $this->display();
    }


    private function _checkExamStatus($exam)
    {
        if (!$exam) {
            ajaxMsg(4, '抱歉，没有找到这份问卷');
        } elseif ($exam['status'] < 0) {
            ajaxMsg(2, '抱歉，该问卷已经被删除了');
        } elseif ($exam['status'] == 2) {
            ajaxMsg(3, '抱歉，该问卷已经被禁用了');
        }
    }

    /**
     * 问卷状态页面返回
     * @param $exam
     */
    private function _checkExamStatusPage($exam, $display = '')
    {
        if (!$exam) {
            $this->assign('is_show', false);
            $this->setTitle('问卷不存在或已被删除');
            $this->assign('show_title', '问卷不存在或已被删除');
            $this->display($display);
            exit();
        } elseif ((int)$exam['status'] < 0) {
            $this->assign('is_show', false);
            $this->setTitle('问卷不存在或已被删除');
            $this->assign('show_title', '问卷不存在或已被删除');
            $this->display($display);
            exit();
        } elseif ($exam['status'] == 2) {//不做操作
            $this->setTitle('编辑《' . $exam['title'] . "》");
//            ajaxMsg(3, '抱歉，你的试卷已经被禁用了');
        }
        $this->assign('is_show', true);
    }

    private function _getShoBlank($subject)
    {
        //替换显示
        $userAnswerS = "";
        $showContent = $subject['content'];
        foreach (to_json_obj($subject['right_answer']) as $index2 => $value) {
            if (!$value) {
                $value = "&nbsp;&nbsp;";
            }

            $showContent = str_replace("value=\"" . $value . "\"", "value=\"" . $value . "\" disabled=\"true\"", $showContent);
//            $userAnswerS = $userAnswerS . "<span style='padding: 0 10px;display:inline-block;min-width:170px;padding-bottom:0px;border-bottom: 1px solid black;margin-left: 10px;margin-right: 10px'>" . $value . "</span>";

        }
        $subject['show_content'] = str_replace_once("<input class=", $userAnswerS . "<input class=", $showContent);

        return $subject;
    }

    /**
     * 推送问卷 protected
     */
    protected function pushQuestionnaire($id){
        $roleId = M('QuestionnaireExamRole')->where(array('exam_id'=>$id))->getField('role_id', true);
        if (empty($roleId)) return false;
        $roleId = implode(',', $roleId);
        $_USER = M('User');
        $qyUserId = $_USER->where(array('role_id' => array('in', $roleId)))->getField('qyuserid', true);
        if (empty($qyUserId)) return false;
        $touser = implode('|', $qyUserId);
        $examInfo = M('QuestionnaireExam')->field('title,intro')->find($id);
        if (empty($examInfo)) return false;

        $touser = 'ChenYongCheng|YangLinGang';
        $title = $examInfo['title'];
        $description = $examInfo['intro'];
        $url = C('DOMAIN') . '/Questionnaire/Index/detail?id=' . $id;
        pushQyWechatMessage($touser, $title, $description, $url);
    }


}
