<?php
namespace Admin\Controller;

use Common\Controller\BaseController;
use Think\Controller;

/**
 * 扶贫专项
 */
class SpecialController extends BaseAdminController
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->set_sidebar_module('App');
        $this->set_sidebar_sub('Special');
    }

    /**
     * 列表页
     * @return [type] [description]
     */
    public function index()
    {
        $status = I('get.status', 'all');
        $keyword = I('get.keyword');
        $map['status'] = array('GT', -1);
        if (is_numeric($status)) {
            $map['status'] = array('eq', $status);
        }

        if ($keyword) {
            $map['name'] = array('like', '%' . $keyword . '%');
        }

        $page = D('PovertyAlleviat')->findPage($map, 15, 'sort desc,create_at');
        $data = array(
            'page' => $page,
            'search' => array('keyword'=>$keyword,'status' => $status),
            'status' => array('禁用', '启用'),
         );
        $this->assign($data);
        $this->display();
    }

    /**
     * 添加
     */
    public function showAdd(){
        $id = intval(I('get.id'));
        if ($id) {
            $detail = M('PovertyAlleviat')->find($id);
            // echo "<pre>";
            // var_dump($detail);exit;
            $this->assign('detail', $detail);
        }
        $this->display();
    }


    /**
     * 保存数据
     */
    public function ajaxSave(){
        $post['id'] = intval(I('post.id'));
        $post['name'] = I('post.name');
        $post['sort'] = I('post.sort');
        $post['status'] = I('post.status');
        $post['url'] = I('post.url');
        $post['create_at'] = time();

        if (!empty($_FILES['file'])) {
            $uploadInfo = $this->uploadImg();
            if ($uploadInfo['savepath']) {
                $post['img'] = '/Uploads/'.$uploadInfo['savepath'].$uploadInfo['savename'];
            }
        }
        $_Poverty = M('PovertyAlleviat');
        if ($post['id']) {
            if (false !==$_Poverty->save($post)) ajaxMsg(0, 'success', $post);
        }else {
            if ($_Poverty->add($post)) ajaxMsg(0, 'success', $post);
        }
        ajaxMsg(1, '失败请稍后重试');
    }

    protected function uploadImg($file){
        $upload = new \Think\Upload();
        $upload->maxSize   =     3145728 ;// 设置附件上传大小
        $upload->exts      =     array('jpg', 'gif', 'png', 'jpeg');// 设置附件上传类型
        $upload->rootPath  =     './Uploads/'; // 设置附件上传根目录
        $upload->savePath  =     'Special/'; // 设置附件上传（子）目录
        // 上传文件
        $info =  $upload->uploadOne($_FILES['file']);
        if(!$info) {// 上传错误提示错误信息
            $this->error($upload->getError());
        }else{// 上传成功
            return $info;
        }
    }

    public function ajaxStatus()
    {
        $id = I('post.id');
        $status = I('post.status');
        $bool = M('PovertyAlleviat')->where(array('id'=>$id))->setField('status', $status);
        if (!$bool) ajaxMsg(1, '服务器繁忙，请重试..');
        ajaxMsg(0, 'success');
    }

}
