<?php
namespace Admin\Controller;

use Common\Controller\BaseController;
use Think\Controller;

/**
 * 支部管理
 * Class SystemController
 * @package Admin\Controller
 */
class StandingBookController extends BaseAdminController
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->set_sidebar_module('StandingBook');
    }

    // 支部党员台账列表页
    public function index()
    {
        $this->set_sidebar_sub('index');
        $searchKey = array();

        $keyword = I('keyword');
        if ($keyword) {
            $search['User.realname'] = array('like',"%$keyword%");
            $searchKey['keyword'] = $keyword;
        }
        $branch_id = I('branch_id');
        if ($branch_id) {
            $search['StudyStandingBook.branch_id'] = $branch_id;
            $searchKey['branch_id'] = $branch_id;
        }
        $content_type = I('content_type');
        if (!empty($content_type) && $content_type > -1) {
            $search['StudyStandingBook.content_type'] = $content_type;
            $searchKey['content_type'] = $content_type;
        }
        $classify = I('classify');
        if (!empty($classify) && $classify > -1) {
            $search['StudyStandingBook.classify'] = $classify;
            $searchKey['classify'] = $classify;
        }
        $this->assign('search', $searchKey);

//        $admin = admin();
//        $auth = session_auth();
//
//        if($auth == 2){//总支
//            $search['PartyBranch.branch_hq_id'] = $admin['admin_branch_hq_id'];
//        }elseif($auth == 3){//总支
//            $search['User.branch_id'] = $admin['admin_branch_id'];
//        }

        $search['StudyStandingBook.type'] = 0;
        $page = D('StudyStandingBookView')->find_page($search,"", "","StudyStandingBook.create_time desc",15);
        $branchs = D('PartyBranch')->select();
        $this->assign('branchs', $branchs);
        $this->assign('page', $page);
        $this->display();

    }

    //删除支部党员台账
    public function ajaxDecStandingBook()
    {
        $id = I('id');
        $obj = D('StudyStandingBook')->delete($id);
        ajaxMsg(0, "已删除");
    }


    // 领导表率台账列表页
    public function index_leader()
    {
        $this->set_sidebar_sub('index_leader');
        $searchKey = array();

        $keyword = I('keyword');
        if ($keyword) {
            $search['User.realname'] = array('like',"%$keyword%");
            $searchKey['keyword'] = $keyword;
        }
        $content_type = I('content_type');
        if (!empty($content_type) && $content_type > -1) {
            $search['StudyStandingBook.content_type'] = $content_type;
            $searchKey['content_type'] = $content_type;
        }
        $this->assign('search', $searchKey);

//        $admin = admin();
//        $auth = session_auth();
//
//        if($auth == 2){//总支
//            $search['PartyBranch.branch_hq_id'] = $admin['admin_branch_hq_id'];
//        }elseif($auth == 3){//总支
//            $search['User.branch_id'] = $admin['admin_branch_id'];
//        }

        $search['StudyStandingBook.type'] = 2;
        $page = D('StudyStandingBookView')->find_page($search,"", "","StudyStandingBook.create_time desc",15);
        $this->assign('page', $page);
        $this->display();
    }

    // 领导表率台账列表页
    public function index_organization()
    {
        $this->set_sidebar_sub('index_organization');
        $searchKey = array();

        $keyword = I('keyword');
        if ($keyword) {
            $search['User.realname'] = array('like',"%$keyword%");
            $searchKey['keyword'] = $keyword;
        }
        $organization_id = I('organization_id');
        if ($organization_id) {
            $search['StudyStandingBook.organization_id'] = $organization_id;
            $searchKey['organization_id'] = $organization_id;
        }
        $content_type = I('content_type');
        if (!empty($content_type) && $content_type > -1) {
            $search['StudyStandingBook.content_type'] = $content_type;
            $searchKey['content_type'] = $content_type;
        }
        $this->assign('search', $searchKey);

//        $admin = admin();
//        $auth = session_auth();
//
//        if($auth == 2){//总支
//            $search['PartyBranch.branch_hq_id'] = $admin['admin_branch_hq_id'];
//        }elseif($auth == 3){//总支
//            $search['User.branch_id'] = $admin['admin_branch_id'];
//        }

        $search['StudyStandingBook.type'] = array('gt',"2");
        $page = D('StudyStandingBookView')->find_page($search,"", "","StudyStandingBook.create_time desc",15);
        $organizations = D('PartyOrganization')->select();
        $this->assign('organizations', $organizations);
        $this->assign('page', $page);
        $this->display();
    }

    // 添加领导表率台账
    public function standingBookAdd()
    {
        $admin = admin();
        $auth = session_auth();

        $leaders = D('UserView')->where(array('adm_id'=>3))->select();
        $this->assign('leaders', $leaders);

//        exit("leaders = " . to_json_string($leaders));

        // 获取角色列表
        $roleList = D('Role')->select();
        $this->assign('roleList', $roleList);

        $id = I('id');
        if ($id) {//如果是编辑，解析接收角色和接收支部
            $detail = D('Todo')->find($id);
            $roles = explode(',', $detail['receiver_roles']);
            $receiverBranchs = explode(',', $detail['receiver_branchs']);
            $detail['roles'] = $roles;
            $detail['branchs'] = $receiverBranchs;
            $this->assign('detail', $detail);
        }

        $this->assign('p', I('get.p', 1));
        $this->display();
    }

    public function ajaxAdd($id = 0){
        $auth = session_auth();
        if ($auth > 0){

            $data['theme'] = I('post.theme');
            if(empty($data['theme'])){
                ajaxMsg(1,"您忘了填标题了");
            }
            $data['host'] = I('post.host');
            if(empty($data['host'])){
                ajaxMsg(1,"您忘了填主持人了");
            }

            $data['uid'] = I('post.leader');
            $data['content_type'] = I('post.contentType');
            $data['classify'] = I('post.classify');
            $data['attendance'] = I('post.attendance');
            $data['attendee'] = I('post.attendee');
            $data['attend_time'] = I('post.attendTime');
            $data['content'] = $_POST['content'];

            $data['adder_uid'] = admin_uid();
            $data['type'] = 2;
            $data['create_time'] = time();

            $id = I('post.id');
            $articleModal = D('Articles');
            if ($id > 0) {
                D('StudyStandingBook')->save($data);
            }else{
                D('StudyStandingBook')->add($data);
            }

            ajaxMsg(0, '保存成功');
        }else{
            ajaxMsg(1, '权限不足');
        }
    }

}