<?php
namespace Admin\Controller;

use Admin\Model\AdminAuthRuleViewModel;
use Common\Controller\BaseController;
use Think\Controller;
use Admin\Util\AdminUtil;

/**
 * 文章管理
 * Class ContentController
 * @package Home\Controller
 */
class TaizhangController extends BaseAdminController
{

	function _initialize()
	{
		parent::_initialize();
		// TODO: Change the autogenerated stub
		$this->set_sidebar_module('Taizhang');

	}

	public function index1()
	{
		$this->set_sidebar_sub('index1');

		$map = array();
		$map['Taizhang.status'] = array('gt', -1);

		$type = I('type', 1);

		$type2 = I('type2', 'all');
		$tag_id = I('tag_id', 'all');
		$norm_id = I('norm_id', 'all');
		$keyword = I('keyword');
		$map['Taizhang.type'] = $type;
		$map['Taizhang.status'] = array('gt', -1);
		if ($type2 != 'all') {
			$map['Taizhang.type2'] = $type2;
		}
		if ($tag_id != 'all') {
			// $map['Taizhang.tag_id'] = array("exp", "in($tag_id)");
			$map['Taizhang.tag_id'] = $tag_id;
		}
		if ($norm_id != 'all') {
			// $map['Taizhang.tag_id'] = array("exp", "in($tag_id)");
			$map['Taizhang.norm_id'] = $norm_id;
		}
		if ($keyword) {
			$map['Taizhang.title'] = array('like', "%" . $keyword . "%");
		}

		$auth = AdminUtil::auth();
		if ($auth == 3) { // 支部管理员
			$branch = AdminUtil::auth_branch();
			$map['Taizhang.branch_id'] = $branch['id'];
		}

		$this->assign('search', array('keyword' => $keyword, 'type' => $type, 'type2' => $type2, 'tag_id' => $tag_id, 'norm_id' => $norm_id));
		$this->assign('page', D('TaizhangView')->findPage($map, 15, 'create_time desc'));
		$this->assign('tags', D('TaizhangTags')->select());
		$this->assign('norms', D('TaizhangNorms')->where(array('type' => 1))->select());
		$this->display();
	}


	public function index()
	{
		$this->index1();
	}

	public function index2()
	{
		$this->set_sidebar_sub('index2');
		$type = I('type', 2);
		$type2 = I('type2', 'all');
		$tag_id = I('tag_id', 'all');
		$norm_id = I('norm_id', 'all');
		$organization_id = I('organization_id', 'all');
		$keyword = I('keyword');
		$map['Taizhang.type'] = $type;
		$map['Taizhang.status'] = array('gt', -1);
		if ($type2 != 'all') {
			$map['Taizhang.type2'] = $type2;
		}
		if ($tag_id != 'all') {
			// $map['Taizhang.tag_id'] = array("exp", "in($tag_id)");
			$map['Taizhang.tag_id'] = $tag_id;
		}
		if ($norm_id != 'all') {
			// $map['Taizhang.tag_id'] = array("exp", "in($tag_id)");
			$map['Taizhang.norm_id'] = $norm_id;
		}
		if ($organization_id != 'all') {
			// $map['Taizhang.tag_id'] = array("exp", "in($tag_id)");
			$map['Taizhang.organization_id'] = $organization_id;
		}
		if ($keyword) {
			$map['Taizhang.title'] = array('like', "%" . $keyword . "%");
		}

		$this->assign('search', array('keyword' => $keyword, 'type' => $type, 'type2' => $type2, 'tag_id' => $tag_id, 'norm_id' => $norm_id, 'organization_id' => $organization_id));
		$this->assign('page', D('TaizhangView')->findPage($map, 15, 'create_time desc'));
		$this->assign('tags', D('TaizhangTags')->select());
		$this->assign('norms', D('TaizhangNorms')->where(array('type' => 2))->select());
		$this->assign('organizations', D('PartyOrganization')->select());
		$this->display();
	}

	public function index3()
	{
		$this->set_sidebar_sub('index3');
		$type = I('type', 3);

		$type2 = I('type2', 'all');
		$tag_id = I('tag_id', 'all');
		$norm_id = I('norm_id', 'all');
		$keyword = I('keyword');
		$map['Taizhang.type'] = $type;
		$map['Taizhang.status'] = array('gt', -1);
		if ($type2 != 'all') {
			$map['Taizhang.type2'] = $type2;
		}
		if ($tag_id != 'all') {
			// $map['Taizhang.tag_id'] = array("exp", "in($tag_id)");
			$map['Taizhang.tag_id'] = $tag_id;
		}
		if ($norm_id != 'all') {
			// $map['Taizhang.tag_id'] = array("exp", "in($tag_id)");
			$map['Taizhang.norm_id'] = $norm_id;
		}
		if ($keyword) {
			$map['Taizhang.title'] = array('like', "%" . $keyword . "%");
		}

		$map['Taizhang.status'] = array('gt', -1);
		$this->assign('search', array('keyword' => $keyword, 'type' => $type, 'type2' => $type2, 'tag_id' => $tag_id, 'norm_id' => $norm_id));
		$this->assign('page', D('TaizhangView')->findPage($map, 15, 'create_time desc'));
		$this->assign('tags', D('TaizhangTags')->select());
		$this->assign('norms', D('TaizhangNorms')->where(array('type' => 3))->select());
		$this->display();
	}

	public function index4()
	{
		$this->set_sidebar_sub('index4');

		$map = array();
		$map['Taizhang.status'] = array('gt', -1);

		$type = I('type', 4);
		$type2 = I('type2', 'all');
		$tag_id = I('tag_id', 'all');
		$norm_id = I('norm_id', 'all');
		$branch_id = I('branch_id', 'all');
		$keyword = I('keyword');
		$map['Taizhang.type'] = $type;
		$map['Taizhang.status'] = array('gt', -1);
		if ($type2 != 'all') {
			$map['Taizhang.type2'] = $type2;
		}
		if ($tag_id != 'all') {
			// $map['Taizhang.tag_id'] = array("exp", "in($tag_id)");
			$map['Taizhang.tag_id'] = $tag_id;
		}
		if ($norm_id != 'all') {
			// $map['Taizhang.tag_id'] = array("exp", "in($tag_id)");
			$map['Taizhang.norm_id'] = $norm_id;
		}
		if ($branch_id != 'all') {
			// $map['Taizhang.tag_id'] = array("exp", "in($tag_id)");
			$map['Taizhang.branch_id'] = $branch_id;
		}
		if ($keyword) {
			$map['Taizhang.title'] = array('like', "%" . $keyword . "%");
		}

		$auth = AdminUtil::auth();
		if ($auth == 3) { // 支部管理员
			$branch = AdminUtil::auth_branch();
			$map['Taizhang.branch_id'] = $branch['id'];
		}

		$this->assign('search', array('keyword' => $keyword, 'type' => $type, 'type2' => $type2, 'tag_id' => $tag_id, 'norm_id' => $norm_id, 'branch_id' => $branch_id));
		$this->assign('page', D('TaizhangView')->findPage($map, 15, 'create_time desc'));
		$this->assign('tags', D('TaizhangTags')->select());
		$this->assign('norms', D('TaizhangNorms')->where(array('type' => 4))->select());
		$this->assign('branchs', D('PartyBranch')->select());
		$this->display();
	}

	public function ajaxDec($id = 0)
	{
		$item = D('Taizhang')->where(array('id' => $id))->find();
		if ($item) {
			D('Taizhang')->where(array('id' => $id))->save(array('status' => -1));
			if ($item['status'] > -1 && $item['add_uid'] != null) {
				update_user_score($item['add_uid'], -5, 1, '删除台账');
			}
		}

		ajaxMsg(0, '保存成功');
	}

	public function edit()
	{
		$id = I('id');
		$type = I('type');
		$item = D('TaizhangView')->where(array('id' => $id))->find();
		$contents = D('TaizhangContents')->where(array('taizhang_id' => $item['id'], 'status' => 0))->select();
		if ($type == 2) {
			$this->assign('party_organization', D('PartyOrganization')->select());
		}
		$info = D('TaizhangContents')->where(array('taizhang_id' => $id))->select();
		if($info){
			$item['pic_arr'] = $info;
		}
		//var_dump($item);
		$this->assign('item', $item);
		$this->assign('contents', $contents);
		$this->assign('norms', D('TaizhangNorms')->where(array('type' => $type))->select());
		$this->assign('tags', D('TaizhangTags')->select());
		$this->display();
	// echo to_json_string($contents);
	}

	public function add()
	{
		$type = I('get.type') ? I('get.type') : 1;
		$this->set_sidebar_sub('index' . $type);
		if ($type == 2) {
			$this->assign('party_organization', D('PartyOrganization')->select());
		}
		$this->assign('norms', D('TaizhangNorms')->where(array('type' => $type))->select());
		$this->assign('tags', D('TaizhangTags')->select());
		$this->assign('type', $type);
		$this->display();
	}

// public function change(){
// 	$admins=D('User')->where(array('post_id'=>1))->select();
// 	foreach ($admins as $key => $vo) {
// 		D('User')->where(array('uid'=>$vo['uid']))-> save(array('is_leader' => 1));

// 	}
// }

	public function ajaxTaizhangAdd()
	{
		$tz = I("post.tz");
		//$contents = I("post.contents");
		$image_path = null;
		// foreach ($contents as $content) {
		// 	if ($content["image"] != null && $content["image"] != '') {
		// 		$image_path = $content["image"];
		// 		break;
		// 	}
		// }
		$uid = '';
		$organization_id = '';
		$branch_id = '';
		if ($tz["type"] == 2) {
			$organization_id = $tz['organization_id'];
		} else {
			$user = D('UserView')->where(array('uid' => $tz['uid']))->find();
			$branch_id = $user["branch_id"];
			$uid = $user["uid"];
		}
		$auth = AdminUtil::auth();
		$admin = AdminUtil::admin();
		if ($auth > 1) { // 支部管理员
			$branch = AdminUtil::auth_branch();
			$branch_id = $branch['id'];
		}

		$tz_id = D("Taizhang")->add(array('tz_content'=>$tz["tz_content"],
			"uid" => $uid, "title" => $tz["title"], "publish_time" => $tz["time"], "type" => $tz["type"], "type2" => $tz["spec_id"], "template_id" => 3, "address" => $tz["address"],
			"tag_id" => $tz["tag_id"], "norm_id" => $tz["norm_id"], "party_name" => $tz["party"], "cover" => $image_path, "organization_id" => $organization_id, "branch_id" => $branch_id, "create_time" => time(), "add_uid" => $admin['uid']
		));
		// foreach ($contents as $content) {
		// 	D('TaizhangContents')->add(array(
		// 		"type" => $content["type"], "image" => $content["image"],
		// 		"content" => $content["content"], "taizhang_id" => $tz_id
		// 	));
		// }

		if ($admin) {
			update_user_score($admin['uid'], 5, 1);
		}
		ajaxMsg(0,'ok', $tz_id);
	}

	public function ajaxTaizhangEdit()
	{
		$tz = I("post.tz");
		//var_dump($tz);
		//$contents = I("post.contents");
		$item = D('Taizhang')->where(array('id' => $tz['id'], 'status' =>array('gt',-1)))->find();
		if ($item) {
		// 	foreach ($contents as $content) {
		// 		if ($content["image"] != null && $content["image"] != '') {
		// 			$image_path = $content["image"];
		// 			break;
		// 		}
		// 	}
			$uid = '';
			$organization_id = '';
			$branch_id = '';
			if ($tz["type"] == 2) {
				$organization_id = $tz['organization_id'];
			} else {
				$user = D('UserView')->where(array('uid' => $tz['uid']))->find();
				$branch_id = $user["branch_id"];
				$uid = $user["uid"];
			}
			$auth = AdminUtil::auth();
			$admin = AdminUtil::admin();
			if ($auth > 1) { // 支部管理员
				$branch = AdminUtil::auth_branch();
				$branch_id = $branch['id'];
			}
			//"publish_time" => $tz["time"],
			D("Taizhang")->where(array('id' => $item['id']))->save(array('tz_content'=>$tz["tz_content"],
				"uid" => $tz['uid'], "status" => $tz['status'], "title" => $tz["title"], "publish_name" => $tz["name"],  "type" => $tz["type"], "type2" => $tz["spec_id"], "template_id" => 3, "address" => $tz["address"],
				"tag_id" => $tz["tag_id"], "norm_id" => $tz["norm_id"], "party_name" => $tz["party"], "cover" => $image_path, "organization_id" => $organization_id, "branch_id" => $branch_id
			));

			// if ($item['template_id'] != 3) {
			// 	$old_content = D('TaizhangContents')->where(array('taizhang_id' => $item['id'], 'status' => 0))->save(array('status' => -1));
			// 	foreach ($contents as $content) {
			// 		D('TaizhangContents')->add(array(
			// 			"type" => $content["type"], "image" => $content["image"],
			// 			"content" => $content["content"], "taizhang_id" => $item['id']
			// 		));
			// 	}
			// }

			ajaxMsg(0, 'ok', $tz['id']);

		} else {
			ajaxMsg(0, '台账不存在或已被删除');
		}

	}

	public function ajaxGetUsers()
	{

		$keyword = I('keyword', '');
		$list = D('UserOrganizationView')->where("User.status=1 and User.realname like '%$keyword%'")->group('User.uid')->order('User.realname asc')->limit(0, 50)->select();
		foreach ($list as $index => $item) {
			$uid = $item["uid"];
			$realname = $item['realname'];
			$mobile = $item['mobile'];
			$item['html'] = "<a style='color: black;cursor: pointer;'><div class='item canselect' data-id='$uid' data-name='$realname'>$realname $mobile</div></a>";
			$list[$index] = $item;
		}

		ajaxMsg(0, 'success', $list);

	}
	#新增文章 ajax提交
	public function ajaxSave()
	{

		$id = I('id');
		$title = I('title');
		$content = $_POST['editorValue'];
		$status = I('status', 1);
		if (!$title) {
			ajaxMsg(1, '请先填写标题');
		}

		if ($id) {
			$array = array('title' => $title, 'content' => $content);
			$detail = D('Taizhang')->where(array('id' => $id))->save($array);
		}

		ajaxMsg(0, '保存成功');
	}


	public function tags()
	{
		$this->set_sidebar_sub('tags');
		$this->assign('page', D('TaizhangTags')->findPage("", 15, 'id desc'));
		$this->display();
	}

	public function addTag()
	{
		$id = I('id');
		if ($id > 0) {
			$detail = D('TaizhangTags')->find($id);
			if ($detail) {
				$this->assign('detail', $detail);
			}
		}
		$this->display();
	}

	public function ajaxAddTag()
	{
		$id = I('id');
		$title = I('title');
		if ($title == "") {
			ajaxMsg(1, "标签名不能为空");
		}

		if ($id > 0) {
			$detail = D('TaizhangTags')->find($id);
			if ($detail) {
				$detail['title'] = $title;
				D('TaizhangTags')->where("id = $id")->save($detail);
				ajaxMsg(0, "成功修改标签");
			} else {
				ajaxMsg(1, "该标签已不存在");
			}
		} else {
			$detail = array('title' => $title);
			D('TaizhangTags')->add($detail);
			ajaxMsg(0, "标签添加成功");
		}
	}

	public function saveImg()
	{

		$arr = I('img');
		$img_done = I('already_save_arr');
		$id = I('id');
		$path = C('tzpath');
		$result = makePic($arr, $path);
	 
	   //  file_put_contents('./wx343244.txt',var_export($img_done,true));
	   // file_put_contents('./wx3432.txt',var_export($result,true));
		$info = D('TaizhangContents')->where(array('taizhang_id' => $id))->select();

		if ($img_done && $info) {
		   //对比有无删减

			foreach ($info as $k => $v) {
				$flag = 0; //現有的
				foreach ($img_done as $ki => $kv) {


					if ($v['id'] == $kv) { //有，不用刪
						$flag = 1;
						break;
					}
				}

				if ($flag == 0) {
					D('TaizhangContents')->where(array('id' => $v['id']))->delete();
				}
			}
		} elseif ($info && !$img_done) {
		   //全删

			D('TaizhangContents')->where(array('taizhang_id' => $id))->delete();
		}
		if ($result['status'] == 1000) {
			$savedata = $result['data'];
			foreach ($savedata as $v) {
				$data['image'] = $v;
				$data['taizhang_id'] = $id;
				$data['status'] = 0;
				$data['type'] = 4;
				D('TaizhangContents')->add($data);
			}

		}

		ajaxMsg(0, 'ok');
	}
}
