<?php
namespace Admin\Controller;

use Common\Controller\BaseController;
use Think\Controller;

/**
 * 三会一课
 * @author Calvin 2019/1/23
 */
class ThreeMeetingController extends BaseAdminController
{
    const fathername = 'meeting';
    const meetingtype = array('党员大会', '支委会', '党小组会', '党课');
    const basestatus = array(0 => '草稿', 2 => '发出');
    protected $_ThreeMeeting;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->set_sidebar_module('ThreeMeeting');
        $this->set_sidebar_sub('index');
        $this->_ThreeMeeting = D('ThreeMeeting');
    }
    // 支部列表页
    public function index()
    {
        $keyword = I('keyword');
        $status = I('get.status');
        $admin = admin();
        $auth = session_auth();
        $map = array();
        $mission_auth = checkPublishParameter( $admin['uid'],$admin['branch_id'] );
        if($mission_auth){
            $branchId = $admin['branch_id']; //支部管理员
        }else{
            $branchId = I('get.branch_id');
        }
        // 如果是超级管理员就渲染全部数据
        // 否则只能看自己发的
        if (1 !== intval($admin['group_id'])) {
            $map['ThreeMeeting.uid'] = array('eq', $admin['uid']);
        }

        if ($keyword) {
            $map['ThreeMeeting.theme'] = array('like', '%' . $keyword . '%');
        }
        if (is_numeric($status)) {
            $map['ThreeMeeting.status'] = array('eq', $status);
        }else {
            $map['ThreeMeeting.status'] = array('gt', -1);
        }
        if (is_numeric($branchId)) {
            $map['ThreeMeeting.branch_id'] = array('eq', $branchId);
        }
        if ($keyword) {
            $map['ThreeMeeting.theme'] = array('like', '%' . $keyword . '%');
        }
        $lists = D('ThreeMeetingView')->findPage($map, 15, 'create_at desc');

        $this->assign('brancds', M('PartyBranch')->field('id,name')->select());
        $this->assign('page', $lists);
        $this->assign('search', array('keyword' => $keyword, 'status' => $status, 'branch_id' => $branchId));
        $this->assign('status', self::basestatus);
        $this->assign('mission_auth', $mission_auth);

        $this->display();
    }

    // 文件上传
    public function ajaxUploadAnnex()
    {
        $res = uploadAnnex(self::fathername, self::fathername);
        ajaxMsg(200, 'success', $res);
    }

    // 保存
    public function ajaxSave()
    {
        $post['id'] = I('post.id');
        $post['uid'] = admin_uid();
        $post['theme'] = I('post.theme');
        $post['tasks_id'] = I('post.tasks_id');
        $post['branch_id'] = I('post.branchId');
        $post['content'] = I('post.content');
        $post['host_id'] = I('post.hostId');
        $post['meeting_type'] = I('post.meeting_type');
        $post['place'] = I('post.place');
        $post['record_id'] = I('post.recordId');
        $post['remarks'] = I('post.remarks');
        $post['start_time'] = I('post.start_time');
        $post['end_time'] = I('post.end_time');
        $post['party_group_name'] = I('post.party_group_name');
        $post['status'] = I('post.status');
        $post['cx'] = I('post.cx');
        $post['lx'] = I('post.lx');
        $post['qj'] = I('post.qj');
        $post['qx'] = I('post.qx');

        $post['file_id'] = explode(',', I('post.file_id'));
        $post['surplus_file_id'] = explode(',', I('post.surplus_file_id')); // to string

        $post['addFileId'] = getAddFileLists($post['file_id'], $post['surplus_file_id']);
        $post['delFileId'] = getDelFileLists($post['file_id'], $post['surplus_file_id']);
        $res = $this->_ThreeMeeting->addOrupdate($post);
        if (is_array($res) && isset($res['id'])) {
          ajaxMsg(0, 'success', $res);
        }
        ajaxMsg(1, $res.'请重试');
    }

    public function edit()
    {
        $id = I('get.id');

        $info = $this->_ThreeMeeting->editInfo($id);
        if (!empty($info)) {
          $user = M('user')->field('uid,realname')
            ->where(array('branch_id'=> $info['branch_id'],'status'=>'1','role_id'=>'1'))->select();

          foreach ($info['attend'] as $value) {
            $attend[$value['attend_type']][] = $value['uid'];
          }
          unset($info['attend']);
        }
        $exts = array('doc', 'pdf', 'xlsx', 'xls', 'docx');
        foreach ($info['files'] as $k => $v) {
            $file_ext = getFileExtension($v['files_path']);
            //$exts = array('doc', 'pdf', 'xlsx', 'xls', 'docx');
            //好东西，解决安卓不能在线预览文件的工具
            //https://view.officeapps.live.com/op/view.aspx?src=dj.zhzy.net.cn/Uploads/file_wander/2019-05-22/5ce4df3487e8b.doc

            if(in_array($file_ext,$exts)){
                $url = urlencode($v['files_path']);
                $info['files'][$k]['files_path_yulan'] = 'https://view.officeapps.live.com/op/view.aspx?src='.$_SERVER['HTTP_HOST'].$url;
            }
            if ($file_ext == 'jpeg') {
                $info['files'][$k]['type'] = 'png';
            } else {
                $info['files'][$k]['type'] = $file_ext;
            }
        }
        $this->assign('tasks', getTaskaListByStatus(1));
        $this->assign('allUser', getUsersBystatus(1));
        $this->assign('info', $info);
        $this->assign('attend', $attend);
        $this->assign('brancds', getBranchInfo());
        $this->assign('meetingtype', self::meetingtype);
        $this->assign('users', $user);
        $this->display();
    }

    // 渲染添加页面
    public function showAdd()
    {
        $userBranchId = I('get.branchId', admin()['branch_id']);
        $branchId = I('get.branch_id')?I('get.branch_id'):$userBranchId;
        $user = M('user')->field('uid,realname')
        ->where(array('branch_id'=> $branchId,'status'=>'1','role_id'=>'1'))->select();

        $this->assign('tasks', getTaskaListByStatus(1));
        $this->assign('allUser', getUsersBystatus(1));
        $this->assign('users', $user);
        $this->assign('branchid', $branchId);
        $this->assign('brancds', getBranchInfo());
        $this->assign('meetingtype', self::meetingtype);
        $this->display();
    }

    public function ajaxBranchInfo()
    {
        $branchId = I('post.branchId');
        if($branchId){
            $BranchInfo = D('User')->where(array('branch_id'=>$branchId,'status'=>'1','role_id'=>'1'))->field('uid,realname')->select();
        }
        if ($BranchInfo){
            ajaxMsg(0, 'success',$BranchInfo);
        }else{
            ajaxMsg(1, '服务器繁忙，请重试..');
        }

    }

    public function ajaxStatus()
    {
        $id = I('post.id');
        $status = I('post.status');
        $_threemeeting = M('ThreeMeeting');
        $bool = $_threemeeting->where(array('id'=>$id))->setField('status', $status);
        if (!$bool) ajaxMsg(1, '服务器繁忙，请重试..');
        ajaxMsg(0, 'success');
    }

    /**
     * 评论
     */
    public function comment()
    {
        $this->set_sidebar_module('Comment');
        $this->set_sidebar_sub('comment');
        $keyword = I('get.keyword');
        if ($keyword) {
            $map['ThreeMeetingComment.comments'] = array('like', '%' . $keyword . '%');
            $this->assign('keyword', $keyword);
        }
        $_commentList = D('meetingCommentView');
        $map['ThreeMeetingComment.status'] = array('GT', -1);
        $page = $_commentList->findPage($map, 15,'ThreeMeetingComment.create_at desc');
        // echo "<pre>";
        // var_dump($page);exit;
        $this->assign('page', $page);
        $this->display();
    }

    public function updateStatus()
    {
        $commentId = I('post.id');
        $status = I('post.status');
        $_comment = M('ThreeMeetingComment');
        $bool = $_comment->save(array('id'=>$commentId, 'status'=>$status));
        if (false === $bool) ajaxMsg(1, '更新失败。。请重试');
        if (1 == $status) {
            $meetingId = $_comment->where(array(
                'id' => $commentId))->getField('meeting_id');
            setIncComment($meetingId);
        }
        ajaxMsg(0, '更新成功');
    }
}
