<?php
namespace Admin\Controller;

use Admin\Model\AdminAuthRuleViewModel;
use Common\Controller\BaseController;
use Think\Controller;

/**
 * 文章管理
 * Class ContentController
 * @package Home\Controller
 */
class UserFileWanderController extends BaseAdminController
{

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->set_sidebar_module('UserFileWander');
        $this->set_sidebar_sub('index');
    }

    public function index()
    {


        $map = array();
        $map['status'] = array('gt', -1);
        $role_data = C('ROLE_GROUP');
        $page = D('UserFileWander')->findPage($map, 15, 'create_time desc');
        foreach ($page['list'] as $k => &$vl) {
            if ($vl['branch_id']) {
                $branch_text = '';
                $branch_id_arr = explode(',', $vl['branch_id']); //变换时的数组     
                foreach ($branch_id_arr as $v) {
                    //字符串
                    $branch_name = M('party_branch')->where(array('id' => $v))->getField('name');
                    $branch_text = $branch_text . $branch_name . ','; //显示在input中的名字
                }
                $vl['branch_text'] = trim($branch_text, ',');
            }
    
            if ($vl['role_id']) {
                $role_id_arr= explode(',', $vl['role_id']); //变换时的数组
                $role_text = '';
                foreach ($role_id_arr as  $v) {
                    $key = $v - 1;
                    $role_text = $role_text . $role_data[$key]['name'] . ',';
                }
                $vl['role_text'] = trim($role_text, ',');
            }
         }
        $this->assign('page', $page);


        $this->display();
    }

    public function addFileWander()
    {
        $id = I('id');
        $detail = array();
        $branch_data = getBranchInfo();
        $role_data = C('ROLE_GROUP');
        $this->assign('branch_data', $branch_data);
        $this->assign('role_data', $role_data);

        if ($id) {
            $title = '编辑文件';
            //编辑
            //需要组装这几个数组branch_text role_text '{$detail.branch_arr}''{$detail.branch_text_arr}''{$detail.role_arr}''{$detail.role_text_arr}'
            //branch_id = 1,2,3
            $detail = D('UserFileWander')->where(array('id' => $id))->find();
            $detail['date'] = date("Y-m-d",$detail['create_time']) ;
            $detail['branch_arr'] = $detail['branch_id']; //input的value
            $detail['role_arr']  = $detail['role_id']; //input的value
            $detail['branchjs_arr'] = $detail['post_id']; //支部角色input的value
            $detail['dw_arr']  = $detail['dw_id']; //input的value
            $detail['branch_id_arr'] = explode(',', $detail['branch_id']); //变换时的数组
            $detail['role_id_arr'] = explode(',', $detail['role_id']); //变换时的数组
            $detail['branchjs_id_arr'] = explode(',', $detail['branchjs_arr']); //变换时的数组
            $detail['dw_id_arr'] = explode(',', $detail['dw_arr']); //变换时的数组
            foreach ($detail['branch_id_arr'] as $v) {
                //字符串
                $branch_name = M('party_branch')->where(array('id' => $v))->getField('name');
                $branch_text_arr[] = $branch_name; //支部名字数组
                $branch_text = $branch_text . $branch_name . ','; //显示在input中的名字
            }
            $detail['branch_text'] = trim($branch_text, ',');
            $detail['branch_text_arr'] = $branch_text_arr;
            foreach ($detail['role_id_arr'] as  $v) {
                //$v = 2  ==  $role_data = 1
                $key = $v - 1;
                $role_text_arr[] = $role_data[$key]['name']; //角色名字数组
                $role_text = $role_text . $role_data[$key]['name'] . ',';
                //字符串
                // $branch_name = M('party_branch')->where(array('id'=>$v))->getField('name');
                // $branch_text =$branch_text.',' .$branch_name.',';
                // $branch_text_arr[] = $branch_name;
            }
            $detail['role_text'] = trim($role_text, ',');
            $detail['role_text_arr'] = $role_text_arr;
            // var_dump($detail);
//            //file文件显示
//            $file_arr =  M('files')->where(array('files_id' => array('in', $detail['file_id'])))->select();
//            // var_dump($file_arr);
//            foreach ($file_arr as $k => $v) {
//                $file_arr[$k]['type'] = getFileExtension($v['files_path']);
//            }
            $detail['add_name'] = M('user')->where(array('uid' => $detail['uid']))->getField('realname');
            //文件显示
            $file_id = explode(",", $detail['file_id']);//文件id
            foreach ($file_id as $xu){
                $isexist = D('Files')->where(array('files_id'=>$xu))->find();
                if($isexist){
                $file_detail[] = D('Files')->where(array('files_id' => $xu))->find();
                }
            }
            $exts = array('doc', 'pdf', 'xlsx', 'xls', 'docx');
            foreach ($file_detail as $k => $v) {
                $file_ext = getFileExtension($v['files_path']);
                //$exts = array('doc', 'pdf', 'xlsx', 'xls', 'docx');
                //好东西，解决安卓不能在线预览文件的工具
                //https://view.officeapps.live.com/op/view.aspx?src=dj.zhzy.net.cn/Uploads/file_wander/2019-05-22/5ce4df3487e8b.doc

                if(in_array($file_ext,$exts)){
                    $url = urlencode($_SERVER['HTTP_HOST'].$v['files_path']);
                    $file_detail[$k]['files_path_yulan'] = 'https://view.officeapps.live.com/op/view.aspx?src='.$url;
                }
                if ($file_ext == 'jpeg') {
                    $file_detail[$k]['type'] = 'png';
                } else {
                    $file_detail[$k]['type'] = $file_ext;
                }
            }
            $this->assign('file_detail', $file_detail);
        } else {
            //新增
            $user = admin();
            $detail['uid'] = $user['uid'];
            $detail['add_name'] = $user['realname'];
            $detail['create_time'] = time();
            $title = '编辑文件';
        }


        //支部角色
        $map['status_id'] = array('in','1,2,4,5,6,3');;
        $branch_juese = D('PartyPost')->where($map)->select();
        //党委角色
        $map['status_id'] = array('in','1,2,14,13,3');;
        $org_juese = D('PartyPost')->where($map)->select();
        $branch = filejueseorder($branch_juese,'1');//1 支部角色
        $org_juese = filejueseorder($org_juese,'2');//1 党委角色
        //为选中的加一个标识，方便页面显示
        foreach($branch as &$item){
            foreach($detail['branchjs_id_arr'] as $v){
                if($item['status_id'] == $v){
                    $item['choose'] = '1';//1 选中 0不选中
                }
            }
        }
        //为选中的加一个标识，方便页面显示
        foreach($org_juese as &$item){
            foreach($detail['dw_id_arr'] as $v){
                if($item['status_id'] == $v){
                    $item['choose'] = '1';//1 选中 0不选中
                }
            }
        }
        $this->assign('branch', $branch);
        $this->assign('org_juese', $org_juese);
        $this->assign('branchjs_id_arr', $detail['branchjs_id_arr']);
        $this->assign('dw_id_arr', $detail['dw_id_arr']);
        $this->assign('title', $title);
        //   var_dump($detail);
        $this->assign('file_arr', $file_arr);
        $this->assign('detail', $detail);
        // var_dump($detail);
        $this->display();
    }

    //  ajax提交保存
    public function ajaxAdd($id = 0)
    {
        // $auth = session_auth();
        // if ($auth == 1){
        $data['title'] = I('post.title');
        $data['sort'] = I('post.sort') > 0 ? I('post.sort') : 0;
        $data['type'] = I('post.type') > 0 ? I('post.type') : 1; // 默认1=党员之家
        $data['img_url'] = I('post.img_url');
        $data['is_top'] = I('post.is_top');
        $data['url'] = I('post.url');

        $id = I('post.id');
        if ($id > 0) {
            D('Show')->where(array('id' => $id))->save($data);
        } else {
            $data['create_time'] = time();
            D('Show')->add($data);
        }
        ajaxMsg(0, '保存成功');
        //  	}else{
        // ajaxMsg(1, '权限不足');
        //  	}
    }


    public function ajaxUploadAnnex()
    {
        $res = uploadAnnex('file_wander', 'file_wander');
        ajaxMsg(200, 'success', $res);
    }
    public function ajaxDec($id = 0)
    {
        $item = D('UserFileWander')->where(array('id' => $id))->find();
        if ($item) {
            D('UserFileWander')->where(array('id' => $id))->save(array('status' => -1));
            ajaxMsg(0, '删除成功');
        } else {
            ajaxMsg(1, '删除失败');
        }
    }

    //获取用户
    public function  ajaxGetUsers_member()
    {
        $keyword = I('keyword', '');
        if($keyword){
            $user = M('User');
            $map['realname'] = array('LIKE',"%$keyword%");   //模糊查询包含此文字
            $page = $user->where($map)->select();
            $this->assign('keyword', $keyword);
        }else{
            $page = D('User')->select();//select();//limit(0,30)->select();
        }
        foreach ($page as $index => $item) {
            $uid = $item["uid"];
            $realname = $item['realname'];
            $branch_name = $item['branch_name'];
            if($branch_name){
                $name = $item['realname'].$item['mobile'] . "[$branch_name]";
            }else{
                $name = $item['realname'].$item['mobile'];
            }
            $item['html'] = "<a style='color: black;cursor: pointer;'><div class='item canselect' data-id='$uid' data-name='$realname'>$name</div></a>";

            $page[$index] = $item;
        }

        ajaxMsg(0, 'success', $page);

    }

    public function ajaxSaveFile(){
        $postdata = I();
        $id = $postdata['id'];
        $surplus_file_id = explode(",",$postdata['surplus_file_id']);//删除的文件id数组
        $file_id = explode(",",$postdata['file_id']);//全部文件数组
        $save['uid'] = $postdata['uid'];
        $save['title'] = $postdata['title'];
        $save['content'] = $postdata['content'];
        $save['add_name'] = $postdata['add_name'];
        $save['branch_id'] = implode(",",$postdata['branch']);//支部id字符串
        $save['role_id'] = implode(",",$postdata['role']);//可看角色
        $save['post_id'] = implode(",",$postdata['post_role']);//支部角色
        $save['dw_id'] = implode(",",$postdata['dw_role']);//支部角色

        foreach($file_id as $key => $item){
            foreach ($surplus_file_id as $v){
                if($item == $v){
                        unset($file_id[$key]);
                }
            }
        };
        $file_id = array_unique($file_id);   //只留下单一元素
        $file_id = implode(",",$file_id);//转成字符串
        $save['file_id'] = $file_id;//最后保存的file_id
        if($postdata['surplus_file_id']){
            foreach ($surplus_file_id as $item){
                $result = D('Files')->where(array('files_id'=>$item))->delete();
            }
            if(!$result){
                ajaxMsg(1, '删除文件失败');
            }
        }
        if ($id > 0) {
            $save['id'] = $id;
            $save['create_time'] = strtotime($postdata['start_time']);
           $result =  D('UserFileWander')->where(array('id' => $id))->save($save);
        } else {
            $save['create_time'] = time();
            $result = D('UserFileWander')->add($save);
        }
        ajaxMsg(0, '保存成功');
    }

}
