<?php
namespace Admin\Controller;

use Admin\Model\AdminAuthRuleViewModel;
use Common\Controller\BaseController;
use Common\Util\ImageUploadUtil;
use Think\Controller;

/**
 * 文章管理
 * Class ContentController
 * @package Home\Controller
 */
class WorkUnitController extends BaseAdminController
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->set_sidebar_module('PartyBranch');
        $this->set_sidebar_sub('workUnit');
    }
    function ajaxUploadCover(){

        ajaxMsg(0, "success", ImageUploadUtil::upload("partygroup/cover/",'file',array('width'=>200,'height'=>200),array('width'=>80,'height'=>80)));
    }

    public function index()
    {

        $map = array();

        $keyword = I('keyword');
        if ($keyword) {
            $map['PartyGroup.name'] = array('like', '%' . $keyword . '%');
        }
        $this->assign('search',array('keyword'=>$keyword));

            $page =D('WorkUnitView')->find_page($map,'', 'WorkUnit.id', 'WorkUnit.sort desc');
            foreach($page['list'] as $index=>$item){
                $page['list'][$index]['name'] = str_replace(array("\r\n", "\r", "\n"),"<br>", $item['name']);//换行替换显示
            }
            $this->assign('page', $page);

        $this->display();
    }

    public function member(){
        $map = array();
        $id = I('id');
        
        $keyword = I('keyword');
        if ($keyword) {
            $map['User.realname'] = array('like', '%' . $keyword . '%');
        }
        $map['User.party_group_id'] = $id;
        
        $this->assign('search',array('keyword'=>$keyword));

        $page =D('UserPartyGroupView')->find_page($map,'', 'User.uid', 'PartyGroupGl.id desc');

        // $test = D('UserPartyGroupView')->fetchSql(true)->select();
        // var_dump($page);
        $this->assign('party_group_id', $id);
        $this->assign('page', $page);
		 $this->assign('detail', D('PartyGroup')->find($id));

        $this->display();
    }

    public function  ajaxGetUsers()
    {

//ajaxMsg(1,to_json_string($_POST));
        $id = I('id', 0);
        $keyword = I('keyword', '');
        $type = I('type','adm');
		$p_uid = I('uid');
        $list = D('UserOrganizationView')->where("User.status=1 and User.realname like '%$keyword%'")->group('User.uid')->order('User.realname asc')->limit(0, 20)->select();
        foreach ($list as $index => $item) {
            $uid = $item["uid"];
            $realname = $item['realname'];
            $branch_name = $item['branch_name'];
            if($branch_name){
                $name = $item['realname'] . "[$branch_name]".$item['mobile'];
            }else{
                $name = $item['realname'].$item['mobile'];
            }
            $item['html'] = "<a style='color: black;cursor: pointer;'><div class='item canselect' data-id='$uid' data-name='$realname'>$name</div></a>";
            if($type == 'adm'){
            	if($item['adm_organization_uid']){
                    $show = true;
                    if($id){
                    	if($p_uid){
                    		if($item['adm_organization_uid'] == $p_uid){
                            	$show = false;
                        	}
                    	}elseif($item['organization_id'] == $id){
                            $show = false;
                        }
                    }
                    if($show){
                        $item['html'] = "<div class='item un' data-id='$uid' >$name<div class='item-right'>[{$item['adm_organization_name']}-{$item['adm_organization_realname']}-管理员]</div></div>";
                	}
                }
            }elseif($type == 'ms'){
                if($item['ms_uid']){
                    $show = true;
                    if($id){
                        if($item['ms_organization_id'] == $id){
                            $show = false;
                        }
                    }
                    if($show){
                        $item['html'] = "<div class='item un' data-id='$uid' >$name<div class='item-right'>[{$item['ms_organization_name']}-秘书]</div></div>";
                    }
                }
            }else{
            	if($item['organization_id']){
                    $show = true;
                    if($id){
                        if($item['organization_id'] == $id){
                            $show = false;
                        }
                    }
                    if($show){
                        $item['html'] = "<div class='item un' data-id='$uid' >$name<div class='item-right'>[{$item['organization_name']}-成员]</div></div>";
                	}
                }
            }

            $list[$index] = $item;
        }

        ajaxMsg(0, 'success', $list);

    }


    public function edit($id = 0)
    {
        if ($id > 0) {
            $condition['id'] = $id;
            $detail = D('WorkUnit')->where($condition)->find();
           
            $this->assign('detail', $detail);
//exit(to_json_string($detail));
        }
        // $branchs = D('PartyBranch')->select();
        // $this->assign('branchs', $branchs);
        $this->assign('p', I('get.p', 1));
        $this->assign('p', I('get.p', 1));
        $this->display();
    }
    public function edit_member()
    {
        $id = I('id');
        $party_group_id=I('party_group_id');
        if ($id > 0) {
            $condition['User.uid'] = $id;
            $detail = D('UserPartyGroupView')->where($condition)->find();
			
            $this->assign('detail', $detail);
		
        }
        $this->assign('party_group_id', $party_group_id);
        $this->assign('p', I('get.p', 1));
        $this->display();
    }


    public function ajaxDec($id = 0){
            $id = I('id');
            D('WorkUnit')->where(array('id'=>$id))->delete();
       
        ajaxMsg(0, '删除成功');
    }
    public function ajaxDecMember($id = 0){
    	$user = D('User')->find($id);
    //	 D('PartyGroup')->where(array('party_group_id'=>$user['party_group_id'],'organization_uid'=>$id))->delete();
            D('User')->where(array('uid'=>$id))->save(array('party_group_id'=>null));
        ajaxMsg(0, '删除成功');
    }

    public function ajaxSave()
    {

//        ajaxMsg(1,to_json_string($_POST));
        $id = I('id');
        $name = I('name');
        
        $sort = I('sort');
  
        if(!$sort){
            $sort = 0;
        }
        if (!$name) {
            ajaxMsg(1, '请先填写单位名称');
        }
        $array = array(
            'sort'=>$sort,
            'name' => $name,
        );


        // if($ms_uid){
        //     $sj =  D('PartyGropuMs')->where(array('uid'=>$ms_uid))->find();
        //     if($sj && $sj['organization_id'] != $id){
        //         $dangzu = D('PartyOrganization')->find($sj['organization_id']);
        //         ajaxMsg(1,"该用户已担任{$dangzu['name']}的秘书");
        //     }
        // }
        if ($id) {
            $detail = D('WorkUnit')->find($id);
            if (!$detail) {
                ajaxMsg(1, "找不到单位");
            }

         
            D('WorkUnit')->where(array('id'=>$id))->save($array);

        } else {

            // $array['create_time'] = time();
            $id =  D('WorkUnit')->add($array);
            // D('PartyGroupGl')->add(array('party_group_id'=>$id,'uid'=>$gl_uid));
           
        }
        // if($gl_uid){
        //     D('User')->add(array('party_group_id'=>$id,'uid'=>$gl_uid));
        // }


        ajaxMsg(0, '保存成功');
    }

    public function ajaxSaveMember()
    {

        $id = I('id');
        $party_group_id = I('party_group_id');
        // $adm_uid = I('adm_uid');
        $is_sj = I('is_sj',0);
		
        if(!$party_group_id){
            ajaxMsg(1, '参数有误');
        }

        if (!$id) {
            ajaxMsg(1, '请先选择用户');
        }

        $detail = D('User')->find($id);
        if ($detail['party_group_id'] && $detail['party_group_id'] != $party_group_id) {
            $dangzu = D('PartyGroup')->find($detail['party_group_id']);
            ajaxMsg(1, "该用户属于{$dangzu['name']}");
        }

    





      //  D('PartyOrganizationAdm')->where(array('organization_id'=>$organization_id,'organization_uid'=>$id))->delete();
        if($is_sj == 1){
            D('PartyGroupGl')->where(array('party_group_id'=>$party_group_id))->delete();
            D('PartyGroupGl')->add(array('party_group_id'=>$party_group_id,'uid'=>$id));
        }
        D('User')->where(array('uid'=>$id))->save(array('party_group_id'=>$party_group_id));
        ajaxMsg(0, '保存成功');
    }


}